- cScripts/Loadouts/CfgLoadouts_Crew.hpp
Intended loadout no longer fits in the pilot uniform alone, added vest. There must have been a change to pilot coveralls capacity in cavpack 3.40.
Changed helmet to jet pilot helmet, as NVG is no longer built into the heli pilot helmet.
> Update fixed wing loadout

- cScripts/CavFnc/functions/init/DiaryRecord/fn_Doc_MissionControl.sqf
Assuming the CBA class init event handlers work how I think they do (once set at mission start, will run specified code automatically on newly created objects). Also add arguments for starter crate.
> Grammar/punctuation, remove veh/crate init functions

- CfgSettings.hpp
- cScripts/CavFnc/CfgFunctions.hpp
- cScripts/CavFnc/cScripts_preInit.sqf
- cScripts/CavFnc/functions/init/fn_initModules.sqf
- cScripts/CavFnc/functions/modules/fn_moduleApplyFlag.sqf
- cScripts/CavFnc/functions/modules/fn_moduleApplyTailNumber.sqf
- cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
- cScripts/CavFnc/functions/modules/fn_moduleReadyHelicopter.sqf
- init.sqf
Corrects all instances of the misspelling "moduel" to "module" throughout the project, including function files and folder. I've tested the branch ingame and get no compilation errors, though I can't test custom modules because Ares is no longer in the modpack which they depend on. (So this may all have been pointless...)
> Correct Module Spelling

- cScripts/CavFnc/functions/systems/fn_addJump.sqf
- cScripts/CavFnc/functions/systems/fn_doJump.sqf
- Passes only the parachute open height into the jump action and script. The max jump height doesn't need to be passed since it's only used for the condition on the action.
- Changed the action condition to use the max jump height argument, it was previously hard coded.
- Increased action color brightness to be more readable (bright purple)
- Changed action text to "Jump" to avoid confusion with the built in Eject action
> New jump script (fixed parameters)

- init.sqf
Removes the value breaking aircraft radios in init.sqf.
TF_defaultWestAirborneRadio is the default LR radio for aircraft. Someone probably set it to the 7800 thinking it was referring to airborne infantry. Setting this to a short range radio breaks all aircraft builtin long range radio, since it can't find the 7800 in the list of long range radios. We don't need this value at all since the default is the tf_anarc210, the correct blufor aircraft radio.
> Fix aircraft radios

- CfgSettings.hpp
- Lowered the red light time down to 30 from 60
All functions are already loaded AI don't need 60 second to get in position.
> Lowered red light time down to 30 from 60

- cba_settings.sqf
- Fixed mission not over ride local optional settings anymore (Colors and other non-realism related effects.)
- Killed the vanilla squad bar via STHUD
- Removes the options that is optional from the `cba_settings.sqf` (This allow for ace duplex settings to be saved mission to mission and other color changes for players wanting to do those changes.)
> Mission don't over ride local settings anymore

- cScripts/CfgLoadouts.hpp
- cScripts/Loadouts/CfgLoadouts_S5.hpp
When merged this pull request will:
Edit the mentioned files.
Create a class for S5 combat camera that will, for any unit with the variable name S5 to S5_4:
- Change unit loadout to be that of a press journalist.
-  Remove unit damage
- Set post/pre unit init.
- Set captive state - invisible to AI
- When in combination with the correct composition allow access to zeus with limited usage (view only)
> Combat cameraman s5

- cScripts/CavFnc/cScripts_preInit.sqf
- FIXED: Issue were `enable7cavZeusModules` was undefined if not running Achilles (Fixed #231)
> Fixed error when mod is not active

- cScripts/CavFnc/functions/systems/fn_getPlayerName.sqf
- FIXED: Bug when a player did not have a clan tag got a return string `nil` instead of empty
> Fixed mission clan tag bug

- cScripts/CavFnc/functions/modules/fn_moduleCreateFieldHospital.sqf
- cScripts/CavFnc/functions/modules/fn_moduleCreateMedicalCrate.sqf
- cScripts/CavFnc/functions/modules/fn_moduleCreateSpecialWeaponsCrate.sqf
- cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
- cScripts/CavFnc/functions/modules/fn_moduleCreateSupplyCrate.sqf
- FIXED: Maby fixed crates not added to Zeus when crated via a module
Fixed #268
> Possible made crates added to zeus on spawn

- cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
- CHANGED: Classnames for inherited classes not referring root instead of team class
> Classnames for inherited classes not referring root instead of team class

- cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf
- FIXED: 4/2/C/1-7 insignia not being shown in quick selection menu
- FIXED: 2/2/C/1-7 insignia not being shown in quick selection menu
> Fixed 4/2/C/1-7 and 2/2/C/1-7 not being shown

- cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
- Fix undefined variable `_addActionAllowedOnCompany` error on crew chief
I can't find `_addActionAllowedOnCompany` anywhere else, I assume it was just missed in a variable name change?
> Quick selection variable error

- cScripts/CavFnc/CfgFunctions.hpp
- cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
- cScripts/CavFnc/functions/systems/fn_deleteDroppedObjects.sqf
Added fnc_deleteDroppedObjects.
This deletes junk and items on the floor in a given radius around the given object.
If attached to the starter crate junk will be deleted in a given radius (Default 50m) whenever player closes the crate inventory.
Usage:
[this,100] call cScripts_fnc_deleteDroppedObjects;
[_object, 100] call FUNC(deleteDroppedObjects);
This can be used to reduce server load caused by a huge number of junk dropped by players munching on the starter crate.
> Delete junk around starter crate (fn_deleteDroppedObjects)

- cScripts/CavFnc/functions/debug/fn_logWarning.sqf
- FIXED: Warnings being shown as info
> Fixed warning being info

- cScripts/CavFnc/functions/diag/fn_log.sqf
- cScripts/CavFnc/functions/init/fn_initEvents.sqf
- CHANGED: Log message text formating is done in final step instead of the text formating stage
> Make text in final instead of formating

- cScripts/functions/modules/fn_zenModule_callEndex.sqf
- FIXED: Spelling for endex hold fire messages
> Fixed spelling

- cScripts/cScripts_preInit.sqf
- cScripts/functions/init/fn_init_staging.sqf
- cScripts/functions/logistics/fn_doStarterCrate.sqf
- cScripts/functions/systems/fn_addHeal.sqf
- cScripts/functions/systems/fn_addReGear.sqf
- ADDED: Global variable to check for One Life Ops
- CHANGED: Regear no loger heal players
- CHANGED: Regear parameter no does not contain heal boolean.
- CHANGED: Heal actions are now hidden when one life ops are enabled.
> Uno life operation check

- cScripts/functions/mission/fn_addGetOutHelo.sqf
- Added bindable shortcut for vehicle exit
- Keybinding uses `User Acrion 12` for left and `UserAction 13` for right
> Added bindable shortcut for vehicle exit

- cScripts/functions/logistics/fn_createCargoCrate.sqf
- cScripts/functions/modules/fn_zenModule_createMedicalCrate.sqf
- cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
- cScripts/functions/vehicle/fn_vehicle_applyTextures.sqf
- Fixed: ```fn_vehicle_addCosmetics``` applies textures to wrong texture slots on ```I_APC_Wheeled_03_cannon_F```.
- Improved: Medical crate spawned with ```createMedicalCrate``` module now is added to all curators.
> Bug fixes for release candidate

- cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
- Reduces javelins per vehicle from 5 to 3 total.
- Add M995 in small amounts to resupply crate, replacing some tracer magazines.
> Adjust ammo in stryker dragoon

- cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
- cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
ref #913 
- Fixes the spelling error preventing the `Anti-Air` pylon from being loaded.
- Adds a block for debugging when a similar error is thrown. This is active only when debug mode is enabled.
> Fixed spelling error in stryker Anti-Air pylon

- cScripts/functions/testing/fn_testing_loadoutArrays.sqf
- Fix syntax of `typeName` command
> Fixed typeName syntax in fn_testing_loadoutArrays

- cScripts/CfgFunctions.hpp
- cScripts/functions/mission/fn_addGetOutHelo.sqf
- cScripts/functions/mission/fn_addHaloJump.sqf
- cScripts/functions/mission/fn_addLineJump.sqf
- cScripts/functions/vehicle/fn_vehicle_reset.sqf
- Added function to clear and reset a vehicle
> Added function to clear and reset a vehicle

- description.ext
- Removed ACE_Spectator and put in the vanilla spectator so players can hear alive and talk to other dead players when in the spectator camera.
> TFAR Spectator ability to hear others

- init.sqf
- Added in the "enableEnviroment" setting where we can change ambient wildlife, ambient sounds, and wind sound strength.
- Ambient wildlife is turned off and clients see a 5-10+ FPS increase.
> Ambient enviorment wildlife turned off which gives FPS increase.

- cScripts/functions/gear/fn_gear_applyLoadout.sqf
- Abilities are not reset when applying a lodout array or apply a saved loadout
> Abilities are not reset when applying a lodout array or apply a saved loadout

- cScripts/functions/systems/fn_addArsenal.sqf
- Fixed issues were the crate was destroyed prematurely
The arsenal box we used toke advantage of a bug wer you could destroy the box and still be in it.
This is now longer the case and this caused you to be thrown out prematurely.
The box is now deleated after you exist the arsenal instead of during.
**Why is the box deleted?**
The box is deleaded to make it possible to select a new loadout with difrent items. If this was not doen you whould get the same items as befor.
> Fixed issues were the Arsenal was destroyed prematurely

- cScripts/CfgLoadouts.hpp
- cScripts/Loadouts/CfgLoadouts_Special.hpp
- Added S3 Mission controll loadouts
- S3 loadouts have autmated unit variable "S3" This nees testing
> Added S3 Mission control loadouts

- cScripts/functions/mission/fn_addStagingZone.sqf
- Added visible staging zone for non vehicle zones.
This feature was earlier only avalible for debugging.
Closes #1043
> Added visible staging zones for non-vehicle zones

- cScripts/functions/init/fn_init_eventHandlers.sqf
- cScripts/functions/systems/fn_addArsenal.sqf
- Added event system for the opening and closing of the crate
Additions to #1058
> Added event system for the opening and closing of the crate

- cScripts/functions/init/fn_init_staging.sqf
- cScripts/functions/mission/fn_addStagingZone.sqf
- cScripts/functions/mission/fn_doStarterCrate.sqf
- cScripts/functions/systems/fn_checkStagingZone.sqf
- Changed marker checks with a simple "whildcard" check instead of activly looking for exact names.
We now accept `zone_staging` and `respawn_west` as well as crazyer names like: `zone_staging_MyZoneHere_123545`
- Zones are now able to be on any kind of marker or object.  Naming a shaped marker zone `zone_staging` will make the staging zone as the shape of the marker.
- Icons will have the same behaviour.
- Startcrate now create a positional zone instead of a object zone.
> Improved and made staging check system more reliable and added the ability to have shaped zones

- cScripts/functions/mission/fn_doStarterCrate.sqf
- Changed starter crate now uses object postion again (Reverted change from #1075)
> Changed starter crate now uses object postion again

- cScripts/functions/civ/fn_civ_init.sqf
- Fixed typo for civilian zone marker names
> Fixed typo for civilian zone marker names

- cScripts/functions/gear/fn_gear_applyLoadout.sqf
- cScripts/functions/init/fn_init_aceArsenal.sqf
- cScripts/functions/systems/fn_addArsenal.sqf
- Changed arsenal whitelist being created on player each time you select laodout instead of each time you open arsenal.
- Added EventHandler to save arsenal whitelist on on local player
Possible Closes #1136
> Changed player arsenal whitelist to be created on loadout application instead of each time arsenal is opened

- cScripts/functions/systems/fn_getArsenalWhitelist.sqf
- cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
- Fix missing quotes in GET_CONTAINER parameter for HMMWV weapons inventory.
- Fix all missing quotes in all calls of GET_CONTAINER_KEYS.
> Fixed missing quotes in HMMWV inventory getter

- cScripts/functions/init/fn_init_logistics.sqf
Added:
- 5 magazines for DMR so we can re-supply them in the field.
Shifted Mortar ammo and MAAWS ammo toward the ammo we use during OP. The crate inventory size is not exceeded.
> Added DMR Ammo and rebalanced mortar ammo

- cScripts/functions/init/fn_init_logistics.sqf
- cScripts/functions/systems/fn_getArsenalWhitelist.sqf
- Expand the arsenal weapon system by adding launcher and handgun slots to the weapons specific system.
> Updated the weapons specific arsenal to add launcher and handgun slots

- cScripts/functions/systems/fn_getArsenalWhitelist.sqf
- Remove "medicGear" from whitelist variables to avoid script error.
> Removed "medicGear" from whitelist variables again

- cScripts/cScripts_preInit.sqf
- cScripts/functions/gear/fn_gear_saveLoadout.sqf
- cScripts/functions/systems/fn_filterUnitLoadout.sqf
- Fix a bug that causes duplicate radio ids to spawn with TFAR.
- Actually implement `fn_filterUnitLoadout`.
> Fixed TFAR radio duplication bug

- cScripts/functions/mission/fn_addLineJump.sqf
Supposedly enable the jump script for the MH-47 variants.
> Updated MH-47 Support for Jump Script

- cScripts/functions/init/fn_init_pylons.sqf
> Fixed undefined variables

- cScripts/CfgFunctions.hpp
- cScripts/functions/gear/fn_gear_getLoadoutDisplayName.sqf
- cScripts/functions/init/fn_init_chatCommands.sqf
- Added `cScripts` chat command to give you cscripts version
- Added `loadout` chat command to give you loadout name
> Added cScripts and loadout chat command  to give you cscripts version and loadout name

- cScripts/functions/init/fn_init_eventHandlers.sqf
- Added better handling for offline checks on player logging to prevent empty object
> Added better handling for offline checks on player logging to prevent empty object

- cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
Fixed error in call to addLineJump.
> Fixed bug were haloJump and lineJump script were mixed up

- cScripts/cScripts_logistics.sqf
After talking with Company Co, we added the missing winter camouflage for our helmets since we already have the rest of the winter camo whitelisted and approved.
> Added missing winter camo for helmets

- Compositions/1.Cav_Viking_Platoon/composition.sqe
Viking squads had riflemens as base units instead of the grenadiers in most of their squads which made them load in with rifleman loadouts instead of grenadier loadouts.
> Fixed missing genadiers in Viking Compositions

- cba_settings.sqf
Added Death & Hit reactions CBA Settings
> Added Death & Hit reactions CBA Settings

- cba_settings.sqf
disabled ear ringing and set explosion deafness coefficient to 0
- Adjusted hearing settings and made ringing optional
> Adjusted hearing settings and made ringing optional
