7Cav/cScripts

cScripts/CavFnc/functions/supplies/fn_equipCrateAmmo.sqf
cScripts/CavFnc/functions/supplies/fn_equipCrateExplosives.sqf
cScripts/CavFnc/functions/supplies/fn_equipCrateGrenades.sqf
cScripts/CavFnc/functions/supplies/fn_equipCrateLaunchers.sqf
cScripts/CavFnc/functions/supplies/fn_equipCrateSpecialWeapons.sqf
cScripts/CavFnc/functions/supplies/fn_equipCrateWeapons.sqf

- Fixed bug `setObjectTexture` not `Global` (`addMagazineCargoGlobal`)

FIXED setObjectTexture not Global

---

cScripts/CavFnc/functions/init/fn_initMissionStartObjects.sqf

NOTE: The Zeus deploy crates will not work. need to be Timed or something in order to work.
* Fixed #6

Fixes the crash bug

---

cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf

- Added Fixed-wing Pilot to quick selections

Added Fixed-wing Pilot to quick selections

---

cScripts/CavFnc/functions/init/fn_initMissionStartHint.sqf

- Increased time for Red Light, Green Light hint. From 30 to 60sec

Increased time for Red Light, Green Light hint

---

README.md
cScripts/Loadouts/CfgLoadouts_Basic.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp

Loadout Update

---

cScripts/CfgACESettings.hpp

- Fixed platoon medics not able to use Surgical Kit (#24)

Varries Bug Fixes

---

CfgSettings.hpp

- Fixed AI setting not being set to default.

Fixed AI setting not being set to default.

---

cScripts/CfgACESettings.hpp

Fixed instant death setting being wrong

Fixed instant death setting being wrong

---

cScripts/Loadouts/CfgLoadouts_Basic.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp

- Re enabled set medical settings via poppy.

Re enabled set medical settings via poppy

---

cScripts/Loadouts/CfgLoadouts_Basic.hpp

Changed Backpacks for CLS

---

cScripts/CavFnc/functions/supplies/fn_doAmmoCrate.sqf
cScripts/CavFnc/functions/supplies/fn_doExplosivesCrate.sqf
cScripts/CavFnc/functions/supplies/fn_doGrenadesCrate.sqf
cScripts/CavFnc/functions/supplies/fn_doLaunchersCrate.sqf
cScripts/CavFnc/functions/supplies/fn_doSpecialWeaponsCrate.sqf
cScripts/CavFnc/functions/supplies/fn_doWeaponsCrate.sqf

Updated Supply crates to handle more crate variants for texture change

Updated standard crates

---

cScripts/CavFnc/functions/systems/fn_addReGear.sqf

Re gear heal change

---

cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf

Fixed Squad Insignia 3/1/C/1-7 not being in charlie category.

Fixed Squad Insignia 3/1/C/1-7 not being in charlie category.

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/init/fn_initModules.sqf
cScripts/CavFnc/functions/modules/fn_moduleMakeEngineer.sqf
cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf
cScripts/Loadouts/CfgLoadouts_Bravo.hpp
cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp
cScripts/Loadouts/CfgLoadouts_Ranger.hpp
cScripts/Loadouts/CfgLoadouts_S3.hpp

Added new Zeus moduel: Assign Engineer
Added is EOD check to setPlayerInitSettings
Added EOD ability to Officers, Charlie weapons units, Rangers and S3
Renmed Make Doctor to Assign Doctor

Module and EOD update

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf

Fixed bug for the startercrate were selecting full selected two values.

Bugfixes to starter crate 

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/Loadouts/CfgLoadouts_Alpha.hpp
cScripts/Loadouts/CfgLoadouts_Bravo.hpp
cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp
cScripts/Loadouts/CfgLoadouts_Medical.hpp
cScripts/Loadouts/CfgLoadouts_Ranger.hpp
cScripts/Loadouts/CfgLoadouts_Training.hpp
cScripts/Loadouts/script/CfgPoppy.hpp
cba_settings.sqf

- Adjusted and fixed radio for all units
- Changed Charlie default Uniform to LOP_U_ISTS_Fatigue_19
- Fixed typo in radio presets
- Adjusted cba settings
- Added rhs_weap_m72a7 from charlie crate

Radiofixno2

---

cScripts/Loadouts/CfgLoadouts_Training.hpp

Fixed backpack duplicate

---

CfgSettings.hpp
cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/cScripts_postInit.sqf
cScripts/CavFnc/functions/init/fn_initC130.sqf
cScripts/CavFnc/functions/init/fn_initCuratorC130.sqf
cScripts/CavFnc/functions/systems/fn_addJump.sqf
cScripts/CavFnc/functions/systems/fn_doJump.sqf

- Fixes #110 
- Makes action auto deploy to the airframe
- Adds a new option to cfgSettings for deployment

Fixed cav jump script

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf

Added explosives to charlie

---

cScripts/Loadouts/CfgLoadouts_Bravo.hpp
cScripts/Loadouts/CfgLoadouts_Charlie.hpp

- Added Android devices to Bravo and Charlie Team Leaders

Added Android devices to Bravo and Charlie Team Leaders

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/init/fn_initModules.sqf
cScripts/CavFnc/functions/logistics/fn_doMedicalCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduelCreateMedicalCrate.sqf

- Added medical resupply crate moduel
- Adjusted medical crate inventory

Added medical crate moduel

---

cScripts/CavFnc/functions/systems/fn_addJump.sqf

- Fixes height not being calculated from sea level.

Fixed height not being calculated from sea level.

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/logistics/fn_doSupplyCrate.sqf

- Added Chemlight Shields to Crates

Added Chemlight Shields to Crates

---

tools/build.py

- Updated build script to be able to build public version of cScripts
- I also did some cleanup.

Updated build script to be able to build public version of cScripts

---

tools/build.py

- Added additional item remover 
- Added auto name tag from -public

Build script Public update

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/init/fn_initModules.sqf
cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
cScripts/CavFnc/functions/modules/fn_moduleRegearTrooper.sqf

- Added new module `Regear Trooper`
- Added new module `Call Endex `
- Fixed missing semicolon

Added New modules 

---

cScripts/CavFnc/functions/init/fn_initModules.sqf
cScripts/CavFnc/functions/modules/fn_moduleApplyFlag.sqf

- Added support for the flag module to add flag to vehicles.

Added support for some vehicles to carry flag and updated the script

---

cScripts/CavFnc/functions/systems/fn_setPostInitPlayerSettings.sqf

- Weapon only safe and never unsafe on loadout selection
- Put in Earplug code cleanup

Made weapon safe only and not unsafe and cleaned earplugs code

---

cScripts/CavFnc/functions/texture/fn_createVehicleLable.sqf
cScripts/CavFnc/functions/texture/fn_setVehicleLable.sqf

- Added eventHandler to handle labels in case of the destruction of a vehicle.
- Added eventHandler to handle labels in case of the removal of a vehicle.

Added eventHandler to handle labels in case of the death of a vehicle.

---

cScripts/CavFnc/functions/logistics/fn_doFieldHospital.sqf
cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf
cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
cScripts/CavFnc/functions/systems/fn_addArsenal.sqf
cScripts/CavFnc/functions/systems/fn_addHeal.sqf
cScripts/CavFnc/functions/systems/fn_addInsigniaSelection.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelection.sqf
cScripts/CavFnc/functions/systems/fn_addReGear.sqf

- Added distance check to all addActions for the Starter Crate to avoid cross map regear.

Added distance check to all addActions for the Starter Crate

---

cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf

Made endex moduel to be run on all clients

---

cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/modules/fn_moduelCreateFieldHospital.sqf
cScripts/CavFnc/functions/modules/fn_moduelCreateMedicalCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduelCreateSpecialWeaponsCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduelCreateSupplyCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduleApplyVehicleLable.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
cScripts/CavFnc/functions/texture/fn_getVehicleLable.sqf

- Changed Setting vehicle inventory to false (needs rework)
- Fixed weirdness in parameters for modules.
- Made use of macros in functions.
- Updated classnames for UH60

Cleanup and classname Update

---

cScripts/CavFnc/cScripts_postInit.sqf
cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/init/fn_initVehicle.sqf
cScripts/CavFnc/functions/systems/fn_addGetOutHelo.sqf
cScripts/CavFnc/functions/systems/fn_addJump.sqf
cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf
cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf
cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf
cScripts/CavFnc/functions/texture/fn_createVehicleLable.sqf
cScripts/script_macros.hpp

- Changed some variables to use EGVAR instead of GVAR

Changed some variables to use EGVAR instead of GVAR

---

cScripts/CavFnc/functions/debug/fn_logError.sqf
cScripts/CavFnc/functions/debug/fn_logInfo.sqf
cScripts/CavFnc/functions/debug/fn_logWarning.sqf

- Debug functions now use PREFIX include instead of its own prefix.
- Fixed params

Debug functions update

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf

- Added `343 Radio` to all starter crates.
- Added `Laser Pointer (Red)` to all starter crates.
- Cleaned up among macro usage in the starter crate.

Cleanup and additions to starter crate

---

cScripts/CavFnc/functions/modules/fn_moduleApplyVehicleLable.sqf

- Added check for already added labels for the label module

Added check for already added labels for the label module

---

cba_settings.sqf

- Added more optional settings
- Enabled advanced ballistic

Settings changes

---

tools/build.py

Adjusted tool

---

cScripts/script_component.hpp

- Update to internal build version 4.2.10

Update to internal build version 4.2.10

---

cScripts/CavFnc/CfgFunctions.hpp

Removed weird comment

---

cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
cScripts/CavFnc/functions/documents/fn_Doc_MissionControl.sqf
cScripts/CavFnc/functions/init/fn_initModules.sqf
cScripts/CavFnc/functions/texture/fn_getVehicleLable.sqf
cScripts/CavFnc/functions/texture/fn_setVehicleLable.sqf
cScripts/Loadouts/script/CfgPoppy.hpp

- Added ability to see the server name in info document
- texture labels are no longer cap sensitive
- Various document cleanups

Cleanup and quality of life update

---

cScripts/CavFnc/functions/systems/fn_setPostInitPlayerSettings.sqf

- Weapons now only safe and never unsafe when obtaining gear.

Weapons now only safe and never unsafe when obtaining gear

---

cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/init/fn_initVehicle.sqf
cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf

- Added new system to handle vehicle loadouts
- Re-enabled setting for vehicle loadout

Added new system to handle vehicle loadouts

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
cScripts/Loadouts/CfgLoadouts_Alpha.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp

Updated alpha loadouts

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/init/fn_initModules.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateFieldHospital.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateMedicalCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateSpecialWeaponsCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateSupplyCrate.sqf
cScripts/CavFnc/functions/systems/fn_addObjectToCurator.sqf

- Adjustments and fixes to modules
- Fixed error in add to curator script

Adjustments and fixes to modules

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/Loadouts/CfgLoadouts_Ranger.hpp

Adjusted ranger Loadouts

---

tools/build.py

Build tool update

---

cScripts/CfgUnitInsignia.hpp
cScripts/Loadouts/CfgLoadouts_Alpha.hpp
cScripts/ViewingDistance/CfgFunctions.hpp

Fixed indent in configs

---

tools/config_style_checker.py

- Fixed config style checker checking admin folder instead of cscripts folder.

Fixed config style checker

---

cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf
cScripts/Loadouts/CfgLoadouts_Alpha.hpp
cScripts/Loadouts/CfgLoadouts_AlphaClass.hpp
cScripts/Loadouts/CfgLoadouts_Bravo.hpp
cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp
cScripts/Loadouts/CfgLoadouts_Medical.hpp
cScripts/Loadouts/CfgLoadouts_S3.hpp
cScripts/Loadouts/CfgLoadouts_Training.hpp

- Fixed engineer not set due to being bool instead of number

Fixed engineer not set due to being bool instead of number

---

cScripts/script_component.hpp

Version Update 4.2.11

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf

- ADDED: Ranger now has `B_AssaultPack_cbr` in their crate.

Added B_AssaultPack_cbr to ranger crate

---

cScripts/script_component.hpp

Version update for internal build

---

cScripts/Loadouts/CfgLoadouts_Ranger.hpp

- [FIXED] Fixed issues with ranger loadouts not applying engineer properly causing loadouts not to get applied at all after medic been loaded.
- [FIXED] A faulty comma in ranger loadouts.

Fixed issues with ranger loadouts not loaded.

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelection.sqf
cScripts/CavFnc/functions/systems/fn_getCompanyVariable.sqf
cScripts/CavFnc/functions/systems/fn_hasCompanyVariable.sqf
cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf

- [FIXED] Fixed way back leftover typo were company were labeled platoon.

Fixed way back leftover typo were company were labeled as platoon.

---

cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf
cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf

- Adjusted endex message
- Added check for params in preinit for player

Endex and debug fixes

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/Loadouts/CfgLoadouts_AlphaClass.hpp
cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/script_component.hpp
tools/build.py

- REMOVED: All TF47 equipment
- Adjusted build tool

Removed TF47 and updated tools

---

cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/systems/fn_setPostInitPlayerSettings.sqf

- ADDED blacklist for some eyewear to allow some user preferred facewear.
- ADDED mission setting to allow to turn on and off the blacklist
- CHANGED renamed setting category `4; Player Actions` to `4; Player`
- CHANGED move and reordered were postLoadout debug messages is printed.

Added blacklist check for eyewere

---

cScripts/CavFnc/functions/init/fn_initCuratorObjectPlaced.sqf
cScripts/CavFnc/functions/systems/fn_setPostInitPlayerSettings.sqf

- Fixes issues after the merge

Post merge fixes

---

cScripts/CavFnc/cScripts_preInit.sqf

- Fixed some spelling and made settings clearer

Cleaned up cScripts settings

---

cScripts/CavFnc/functions/systems/fn_getPlayerName.sqf

- FIXED Bug were rank were not trimmed when name were fetched.

Fixed bug were rank tag were not trimmed

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/systems/fn_addInsigniaSelection.sqf
cScripts/CavFnc/functions/systems/fn_getSquadInsignia.sqf
cScripts/CavFnc/functions/systems/fn_setPostInitPlayerSettings.sqf

- ADDED Automated squad insignia application system.
- ADDED Insignia that are selected or spawn with are now saved and reapplied after respawn.

Added automated squad insignia application system

---

cScripts/script_component.hpp

Updated Version

---

README.md

Removed TF47 from the readme

---

cScripts/CavFnc/functions/systems/fn_setPreInitPlayerSettings.sqf

- ADDED player do now have there name stored as a variable.

Added variable to store player name

---

cScripts/CavFnc/functions/systems/fn_doJump.sqf

- ADDED: Minor documentation for doJump.
- CHANGED: doJump function private already being private.

Fixed some documentation and de privat already private

---

cScripts/script_component.hpp

Version update

---

cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
cScripts/CavFnc/functions/players/fn_getSquadInsignia.sqf

- Added alternative naming check for insignia and radio squad channel

Added alternative naming check for insignia and radio squad channel

---

.travis.yml
tools/deploy.py

Added deploy script

---

.travis.yml

Added deploy to travis

---

.travis.yml

Reverted deploy

---

cScripts/CavFnc/functions/systems/fn_addJump.sqf

- Increase speed limit by 10kph

Increase speed limit by 10

---

.travis.yml
tools/build.sh

Script updates

---

tools/build.py

fixed derp

---

cScripts/ViewingDistance/GUI.h

My linter and armake were screaming about it

Adding in semi-colons to end class defs

---

cScripts/Loadouts/CfgLoadouts_Charlie.hpp

- Added DAGR to Charlie Grenadier and Combat Life Saver.

Added dagr to soldier missing one

---

cScripts/CavFnc/functions/players/fn_getCavSquadName.sqf

- Fixed error when player did not have a set unit variable

Fixed Get Squad Name Issue

---

cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf

- Updated insignia documention and fixed typo in debug

Fixed documentation for insignia

---

cScripts/CavFnc/functions/modules/fn_moduleCreateFieldHospital.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateMedicalCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateSpecialWeaponsCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateSupplyCrate.sqf

- Possible fixed object not being added to curator when spawned via module

Possible Fix For Zeus Profiling Take Two

---

tools/build.ini

- Removed check for medical in build.ini

Removed check for medical in build.ini

---

Compositions/Cav_Apollo_Team_Deployment/composition.sqe
Compositions/Cav_Apollo_Team_Deployment/header.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_D/composition.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_D/header.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_W/composition.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_W/header.sqe
Compositions/Cav_Banchee_Team_Deployment/composition.sqe
Compositions/Cav_Banchee_Team_Deployment/header.sqe
Compositions/Cav_Bandit_Deployment/composition.sqe
Compositions/Cav_Bandit_Deployment/header.sqe
Compositions/Cav_Buffalo_Crew_Vehicle_Deployment/composition.sqe
Compositions/Cav_Buffalo_Crew_Vehicle_Deployment/header.sqe
Compositions/Cav_Havoc_Team_Deployment/composition.sqe
Compositions/Cav_Havoc_Team_Deployment/header.sqe
Compositions/Cav_Misfit_Deployment/composition.sqe
Compositions/Cav_Misfit_Deployment/header.sqe
Compositions/Cav_Mustang_Team_Deployment/composition.sqe
Compositions/Cav_Mustang_Team_Deployment/header.sqe
Compositions/Cav_Titan_Crew_Vehicle_Deployment/composition.sqe
Compositions/Cav_Titan_Crew_Vehicle_Deployment/header.sqe
Compositions/Cav_Viking_Deployment/composition.sqe
Compositions/Cav_Viking_Deployment/header.sqe
tools/deploy.sh

Added compositions

---

cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf

- Added a system were your team color is set on spawn based on your name

Team is now set on spawn

---

Compositions/Cav_Apollo_Team_Deployment/header.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_D/header.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_W/header.sqe
Compositions/Cav_Banchee_Team_Deployment/header.sqe
Compositions/Cav_Bandit_Deployment/header.sqe
Compositions/Cav_Buffalo_Crew_Vehicle_Deployment/header.sqe
Compositions/Cav_Havoc_Team_Deployment/header.sqe
Compositions/Cav_Misfit_Deployment/header.sqe
Compositions/Cav_Mustang_Team_Deployment/header.sqe
Compositions/Cav_Titan_Crew_Vehicle_Deployment/header.sqe
Compositions/Cav_Viking_Deployment/header.sqe

Updated header

---

Compositions/Cav_Apollo_Team_Deployment/header.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_D/header.sqe
Compositions/Cav_Apollo_Team_Vehicle_Deployment_W/header.sqe
Compositions/Cav_Banchee_Team_Deployment/header.sqe
Compositions/Cav_Bandit_Deployment/header.sqe
Compositions/Cav_Buffalo_Crew_Vehicle_Deployment/header.sqe
Compositions/Cav_Havoc_Team_Deployment/header.sqe
Compositions/Cav_Misfit_Deployment/header.sqe
Compositions/Cav_Mustang_Team_Deployment/header.sqe
Compositions/Cav_Titan_Crew_Vehicle_Deployment/header.sqe
Compositions/Cav_Viking_Deployment/header.sqe

fixed spelling

---

cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf

- Fixed check and texture path for insignias

Fixed check and texture path for insignias

---

cScripts/Loadouts/CfgLoadouts_Alpha.hpp
cScripts/Loadouts/CfgLoadouts_AlphaClass.hpp

Changed classname

---

Compositions/Cav_0_HQ_Deployment/composition.sqe
Compositions/Cav_0_HQ_Deployment/header.sqe

Added HQ element

---

cScripts/CavFnc/functions/players/fn_getSquadInsignia.sqf
cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
cScripts/CavFnc/functions/systems/fn_addInsigniaSelection.sqf

- ADDED: Insignia are now saved in profile allowing cross mission and server saving

Insignia are now saved in profile

---

cScripts/CavFnc/functions/players/fn_getPlayerRank.sqf

- Added reservist rank to rank check. They always receive Private rank.

Added reservist rank to rank check

---

Compositions/Cav_Banshee_Team_Deployment/composition.sqe
Compositions/Cav_Banshee_Team_Deployment/header.sqe

- Fixed spelling of Banshee composition

Fixed spelling of Banshee

---

cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf

- Rank is only applied if you have cav tag

Rank is only applied if you have cav tag

---

cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf

- Starter crate now allow for company and squad filtering

Starter crate now allow for company and squad filtering

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/systems/fn_addLoadoutAction.sqf

- Added `addLoadoutAction` function allow for addaction loadouts to be created

Added addLoadoutAction function

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
cScripts/Loadouts/CfgLoadouts_Common.hpp
cScripts/Loadouts/CfgLoadouts_Ranger.hpp
cScripts/Loadouts/CfgLoadouts_RangerClass.hpp

- Updated loadouts
- Updated crate inventpory

Rangers and snipers update

---

init.sqf

- CHANGED Cleaned up logging and adjusted the init.sqf

Cleaned up the init

---

cScripts/CavFnc/functions/players/fn_getPlayerRank.sqf

- FIXED Reserve rank being wrongly referenced

Fixed reserve rank being refered wrong

---

Compositions/Cav_Bandit_Deployment/composition.sqe
Compositions/Cav_Misfit_Deployment/composition.sqe

- REMOVED Rifleman from Bandit and Misfit squads
- REMOVED Combat Life Saver from Bandit and Misfit squads
- ADDED Rifleman Light AT

Changed removed RM CLS and added LAT

---

cScripts/CavFnc/functions/players/fn_getPlayerRole.sqf

Fixed role none shown in return when using role description 

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/texture/fn_getVehicleLable.sqf

Fixed merge misses

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/players/fn_getCompanyVariable.sqf
cScripts/CavFnc/functions/players/fn_hasCompanyVariable.sqf
cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
cScripts/CavFnc/functions/players/fn_setPreInitPlayerSettings.sqf
cScripts/CavFnc/functions/players/fn_setTeamColor.sqf

- Removed obsolie and unused Trooper variable
- Moved check and added function to handle team color

Removed variable added and moved function

---

cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf

Fixed dubble private 

---

cScripts/CavFnc/functions/players/fn_getSquadInsignia.sqf

- ADDED Charlie 2 2 insignia
- ADDED Charlie 2 4 insignia

Added new insignias

---

cScripts/CavFnc/functions/selections/fn_initQuickSelections.sqf
cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp

- Major over-hole of the charlie loadout system and loadouts.

Updated charlie loadouts

---

tools/deploy.sh

patch release should now be built

---

Compositions/Cav_Bandit_Deployment/composition.sqe
Compositions/Cav_Buffalo_Crew_Vehicle_Deployment/composition.sqe
Compositions/Cav_Misfit_Deployment/composition.sqe
Compositions/Cav_Titan_Crew_Vehicle_Deployment/composition.sqe

- CHANGED: Compositions to match new CavAddon

Changed Compositions to match new CavAddon

---

cba_settings.sqf

- CHANGED: Lowered time for unloading and loading cargo.
- CHANGED: Lowered time for para dropping cargo to 0.

Adjusted settings for cargo load and drop

---

description.ext

- ADDED: Template for one life op in description.ext

Added one life comment template

---

description.ext

- ADDED: Enabled the vanilla garbage collection system

Enabled the vanilla garbage collection system

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf

Fixed string being string

---

tools/build.py
tools/deploy.sh

Revoked patch

---

tools/build.py

devbuilds now handles in the tagname

---

tools/deploy.sh

Revert "Update deploy.sh"

---

.travis.yml
tools/deploy.sh

- New deploy script
- Changed travis.yml

Update deploy script

---

tools/deploy.sh

- Added files to ignore in on zip for patch

Added files to ignore in on zip for patch

---

cScripts/script_macros.hpp

Removed left over macro

---

cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf

- FIXED: Player being referenced instead of unit parameter

player referenced instead of param unit

---

cScripts/CavFnc/functions/selections/fn_initInsigniaSelections.sqf

- ADDED: CLS, Ranger and Airborn to insignia selector

Added Special insignias to selector

---

cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp

- ADDED: Blue spray paint for Charlie Bandit and Misfit Bravo FTL
- ADDED: Red spray paint for Charlie Bandit and Misfit Alpha FTL
- ADDED: Black spray paint for Charlie Bandit and Misfit SL
- ADDED: Green spray paint for Charlie Bandit and Misfit Staff

Added spray to staff, squads and alpha bravo FTL

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/players/fn_getPlayerClan.sqf
cScripts/CavFnc/functions/players/fn_getPlayerName.sqf
cScripts/CavFnc/functions/players/fn_isPlayerClan.sqf
cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf
cScripts/script_component.hpp

- ADDED: New function `getPlayerClan`
- ADDED: New function `isPlayerClan`
- CHANGED: `getPlayerName` and `setPlayerRank` to use `isPlayerClan`
Close #407

Clan check functions

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf

- ADDED: Charlie crate inventory is readded.

Re added charlie inventory

---

cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf

- FIXED: Hot fixed endex causing issues on `_holdFireMessage`

Hot fixed endex causing issues on holdFireMessage

---

.gitignore
tools/build.ini

- Ignoring doc folder if any exist

Doc ignore

---

.travis.yml

Only check the cscripts script folder

---

cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf

- FIXED: Issue were wrong player being referenced
- CHANGED: Improved the endex module

Adjustments to endex script

---

README.md
cScripts/ViewingDistance/CfgFunctions.hpp
cScripts/ViewingDistance/GUI.h
cScripts/ViewingDistance/defines.h
cScripts/ViewingDistance/fn_onChar.sqf
cScripts/ViewingDistance/fn_onSavePressed.sqf
cScripts/ViewingDistance/fn_onSaveSelectionChanged.sqf
cScripts/ViewingDistance/fn_onSliderChanged.sqf
cScripts/ViewingDistance/fn_onTerrainChanged.sqf
cScripts/ViewingDistance/fn_openMenu.sqf
cScripts/ViewingDistance/fn_openSaveManager.sqf
cScripts/ViewingDistance/fn_stateTracker.fsm
cScripts/ViewingDistance/fn_updateViewDistance.sqf

- CHANGED: Updated TAW VD script

Updated TAWVD

---

tools/generate_wiki_articles.py

Documentation function

---

cScripts/CavFnc/functions/documents/fn_DocChklist_CFF.sqf
cScripts/CavFnc/functions/documents/fn_DocChklist_JMTASKS.sqf
cScripts/CavFnc/functions/documents/fn_DocChklist_LZEXTRACT.sqf
cScripts/CavFnc/functions/documents/fn_DocChklist_LZINSERT.sqf
cScripts/CavFnc/functions/documents/fn_DocChklist_LZSPECS.sqf
cScripts/CavFnc/functions/documents/fn_DocRadio_LACEACE.sqf
cScripts/CavFnc/functions/documents/fn_DocRadio_MEDEVAC.sqf
cScripts/CavFnc/functions/documents/fn_DocRadio_ROTARYPICKUP.sqf
cScripts/CavFnc/functions/documents/fn_DocRadio_SPOTREP.sqf
cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf
cScripts/CavFnc/functions/documents/fn_Doc_MissionControl.sqf

Revert "Date topic removed from diary records"

---

cScripts/CavFnc/functions/players/fn_doPlayerAnnouncement.sqf

- CHANGED: Announcements should now only be applied to clan members

Changed announcement handler

---

cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf

- FIXED: Endex not executing on every client

Fixed endex not executing on everyclient

---

tools/generate_wiki_articles.py

Fixed html not shown

---

cScripts/CavFnc/functions/systems/fn_addQuickSelection.sqf
cScripts/CavFnc/functions/systems/fn_addReGear.sqf
cScripts/Loadouts/script/functions/main/fn_applyLoadout.sqf
cScripts/Loadouts/script/functions/main/fn_selectLoadout.sqf

- Did some rework for saving the loadout.
Fixes  #176

Reworked loadout save

---

cScripts/CavFnc/functions/mission/fn_setVehicleLable.sqf

- FIXED: C130 label being off center

Fixed C130 label 

---

cScripts/ViewingDistance/fn_updateViewDistance.sqf

- FIXED: Server spam caused by TAW_VD script

Possibly fixed server spam

---

cScripts/Loadouts/CfgLoadouts_BravoClass.hpp

- Fixed classses missing class

Fixed classes missing class

---

Compositions/Cav_Viking_Platoon_Deployment_D/composition.sqe
Compositions/Cav_Viking_Platoon_Deployment_W/composition.sqe

Fixed Viking composition

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/players/fn_getSquadName.sqf

- FIXED: Param expecting string instead of object

Fixed param expecting string instead of object

---

Compositions/Cav_Lancer_Deployment/composition.sqe
cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/modules/fn_moduleCreateStarterCrate.sqf
cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf
cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
cScripts/Loadouts/script/CfgPoppy.hpp

- FIXED lancer spellings
- FIXED Missing crate categories
- ADDED Error on wrong or faulty category for crates in dev mode.
- CHANGED Punisher radio removed and replaced with Lancer
- ADDED Warning when player don't have a unit variable set in dev mode.
- ADDED Viking loadouts to loadout selector
- CHANGED Lancer loadouts being named Viking still in loadout selector

Varrius fixes

---

resourses/misc/build.bat
tools/build.py

- Allowed no repo builds using the build script Fixes #478

Allowed no repo builds using the build script

---

tools/sqf_validator.py

Updated validator

---

.github/workflows/deploy.yml

Reworked deployment

---

.github/workflows/deploy.yml

Adjustments

---

.github/workflows/deploy.yml
tools/deploy.sh

New deployment

---

cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf

- Added heal all player option to Endex moduel

added heal all players option

---

cScripts/CavFnc/functions/debug/fn_logError.sqf
cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf

- CHANGED: Errors now print in chat in eden multiplayer and singelplayer
- CHANGED: Crate now exit and throw error when crate category is invalid.

Errors now print in chat

---

Compositions/Cav_Bandit_Deployment/composition.sqe
Compositions/Cav_Misfit_Deployment/composition.sqe

- Replaced Bravo AT with CLS for Misfit
- Replaced Bravo AT with CLS for Bandit

Restored CLS to Bandit and Misfit

---

cScripts/CavFnc/functions/init/fn_initModules.sqf
cScripts/CavFnc/functions/systems/fn_addHeal.sqf
cScripts/Loadouts/script/functions/atomics/fn_replaceItems.sqf
cba_settings.sqf

- FIXED: Errors caused by ACE Medical update
- ADDED: VCOM_AI Settings
- ADDED: USAF Settings
- ADDED: Preset for ace viewing distance limitation usage (off per default)
- CHANGED: More client side customization settings.

ACE release fixes

---

cba_settings.sqf

Fixes to settings

---

tools/generate_wiki_articles.py

- Added user to github user detection

Added user to author detection

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf

- CHANGED: Adjusted ,and cleaned the startercrate

Cleaning in the startercrate

---

cScripts/Loadouts/CfgLoadouts_Common.hpp

- CHANGED: Moved Cav Scout class under bravo for inheritance

Moved cav scout under bravo base

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/helpers/fn_exportContainerToArsenal.sqf
cScripts/CavFnc/functions/helpers/fn_exportLoadoutsToArsenal.sqf

- CHANGED: Updated Export function to handle all child classes instead of hardcode them

Updated Export function

---

cScripts/CavFnc/functions/logistics/fn_doMedicalCrate.sqf

- ADDED: Splint to medical crate
- REMOVED: Size and carry restriction from the medical crate function

Added splint to medical crate

---

cScripts/CavFnc/functions/systems/fn_addArsenal.sqf

- CHANGED: Updated content to match current containers
- CHANGED: Cleaned up and rewrote the function

Updated and rewrote cav arsenal containers

---

cScripts/Loadouts/CfgLoadouts_Charlie.hpp

- FIXED: Radio not applied to charlie Grenadier
- FIXED: Radio not applied to charlie Automatic Rifleman

Adjusted loadouts to fit a 343

---

cba_settings.sqf

- CHANGED: Adjusted medical settings

Changed settings

---

cScripts/CavFnc/functions/systems/fn_addHeal.sqf

- FIXED: Path to medical cross symbol

Fixed path

---

cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf

- REMOVED: Earplugs from vehicles
- ADDED: Wirecutters to transport
- ADDED: Rope to rotary transport if rope system is required

Updated vehicle inventory

---

cScripts/CavFnc/functions/init/fn_initItemReplace.sqf

fixed typo

---

cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf

Fixed comma

---

cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf

fixed usage of old variable

---

cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf

Fixed missing semicolon (bad linter!)

---

cScripts/CavFnc/functions/systems/fn_setVehicleInventory.sqf

fixed errors in script

---

.gitmodules

Removed submoduel

---

cScripts/CavFnc/functions/debug/fn_logError.sqf
cScripts/CavFnc/functions/debug/fn_logInfo.sqf
cScripts/CavFnc/functions/debug/fn_logWarning.sqf
cScripts/CavFnc/functions/init/fn_initStartupHint.sqf

- FIXED: Script headers
- ADDED: Additional example for debug functions.

Fixed some script headers

---

cScripts/CavFnc/functions/players/fn_getSquadName.sqf

- ADDED:  lancer to getSquadName

Added lancer to getSquadName

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/players/fn_setActiveRadio.sqf
cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
cScripts/CavFnc/functions/players/fn_setRadioChannel.sqf

- FIXED: 343 not set to active when more then one radio

Possible fixed 343 not active

---

cScripts/CavFnc/cScripts_postInit.sqf
cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/debug/fn_logError.sqf
cScripts/CavFnc/functions/debug/fn_logInfo.sqf
cScripts/CavFnc/functions/debug/fn_logWarning.sqf
cScripts/CavFnc/functions/init/fn_initACELoadouts.sqf
cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf
cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf
cScripts/CavFnc/functions/players/fn_setPreInitPlayerSettings.sqf

- FIXED: Insignia not being applied properly on mission start
- FIXED: Insignia not being assigned when non were stored
- CHANGED: Improved and updated log messages and the log system

Updated logging and fixed insigna assignation

---

cScripts/Loadouts/CfgLoadouts_Bravo.hpp

- CHANGED: Mustang team gear
- CHANGED: Bravo platoon medic gear

Medical team update

---

cScripts/CavFnc/functions/players/fn_hasCompanyVariable.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelection.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf

- ADDED: Better logging for crates
- FIXED: Variable for mustang medical teams

Updated logs and fixed variable

---

cScripts/Loadouts/CfgLoadouts_Charlie.hpp

- CHANGED: Charlie AR magazine reduced by 1 down to 4.
- CHANGED: Charlie Grenadier HEDP 40mm grenade reduced by 1 down to 16.
- CHANGED: Charlie Grenadier White Smoke 40mm grenade reduced by 1 down to 6.
- CHANGED: Charlie Machinegunner Tracer box reduced by 1 from 5.

Radio for charlie

---

description.ext

- ADDED: Mission now block server setting changes.

added mission setting change block

---

cScripts/CavFnc/cScripts_preInit.sqf

- Added globals for mod checks

Added global checks for mods

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp

Updates all charlie loadouts (built from scratch)
Updates charlie quick selection
Rifleman_LAT will now give a rifleman loadout

Charlie Loadout Updates

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
cScripts/Loadouts/CfgLoadouts_Bravo.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp

Updating bravo loadouts, supply crates, etc

Bravo Loadouts

---

description.ext

Fixed Missing semicolon

---

cScripts/Loadouts/CfgLoadouts_Charlie.hpp

Adding range table to mortar team leader

---

tools/generate_wiki_articles.py

Added wiki link to article

---

cScripts/CavFnc/functions/players/fn_hasCompanyVariable.sqf

- FIXED: documentation script headers

Fixed documentation script headers

---

cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp

Fixed classname issue

---

cScripts/Loadouts/CfgLoadouts_Charlie.hpp

Fixed semicolons

---

cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf

Add 2/2/B Patch

---

tools/build.ini

Fixed gearfiles

---

cScripts/Loadouts/CfgLoadouts_Bravo.hpp
cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
cScripts/Loadouts/CfgLoadouts_Charlie.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp
cScripts/Loadouts/CfgLoadouts_S3.hpp

Fixed configs and added classname proxy

---

README.md

Minor readme formating

---

Compositions/Cav_Training_SOI_Classes_Armed/composition.sqe
Compositions/Cav_Training_SOI_Classes_Armed/header.sqe
Compositions/Cav_Training_SOI_Classes_Unarmed/composition.sqe
Compositions/Cav_Training_SOI_Classes_Unarmed/header.sqe

- Added SOI Classes (Unarmed/BLN/BRCC)
- Added SOI Classes (Armed/BIT/AIT/BLC/Etc.)

Added Blake.H Compositions

---

cScripts/Loadouts/script/CfgPoppy.hpp

- added a semicolon to poppy config

added a ; to poppy config

---

cScripts/CavFnc/functions/players/fn_setTeamColor.sqf

- added charlie and delta team coloring

added charlie and delta team coloring

---

.github/workflows/deploy.yml
tools/build_settings_config.sh
tools/check_loadout_classnames.py
tools/deploy.sh
tools/link_compositions.py

- Added script to build a CBA_Settings pbo
- Added script to check and out put loadouts
- Added script to link compostion with the script working dir

Added new scripts

---

cScripts/CavFnc/functions/players/fn_setPreInitPlayerSettings.sqf
cScripts/CavFnc/functions/systems/fn_addHeal.sqf
cScripts/CavFnc/functions/systems/fn_addReGear.sqf

Fixed healing and engineer

---

cScripts/Loadouts/CfgLoadouts_BravoClass.hpp
cScripts/Loadouts/CfgLoadouts_CharlieClass.hpp

Added officer loadouts

---

cScripts/CavFnc/functions/documents/fn_Doc_MissionControl.sqf
cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
cScripts/CavFnc/functions/players/fn_setPostInitPlayerSettings.sqf

- Added open Zeus interface button in diary record (experimental)
- Added name variations for starter crate label.
- Players now reload there magazine on spawn and gear selections. (Work around for no mag in weapon.)

Quality of life changes

---

cScripts/Loadouts/CfgLoadouts_Training.hpp
cScripts/Loadouts/CfgLoadouts_TrainingClass.hpp

Added Blake TU

---

cba_settings.sqf

- CHANGED: Temperately disabled advanced ballistics
(Until https://github.com/acemod/ACE3/pull/7699 is merged and released)
Close #601

Disabled advanced ballistics

---

cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
cScripts/Loadouts/CfgLoadouts_Bravo.hpp

- Added MMG local classes to lancer

Added MMG local classes to lancer

---

cScripts/CavFnc/functions/players/fn_setPreInitPlayerSettings.sqf

- FIXED: Abitities not being set correctly

Fixed abilities

---

cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/init/fn_initACELoadouts.sqf
cScripts/CavFnc/functions/init/fn_initTagging.sqf
cScripts/CavFnc/functions/init/fn_initVehicle.sqf
cScripts/CavFnc/functions/players/fn_setActiveRadio.sqf
cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf
cScripts/CavFnc/functions/players/fn_setTeamColor.sqf

- FIXED: Typos and spelling
- ADDED: Some minor none player checks
- ADDED: Log category to some logs

Fixed spelling and added additional checks and logging

---

tools/export_classnames.py

Added classname export tool

---

cScripts/CavFnc/functions/modules/fn_moduleCallEndex.sqf

- CHANGED: Endex fire warning now only show once per weapon fired

Made endex less spammy

---

cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf

- Added Gunslinger radio protocol

Added Gunslinger radio protocol

---

cScripts/CavFnc/functions/systems/fn_getVehicleLable.sqf

Fixed Crash

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf
cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp

- FIXED References being wrongly implemented
- CHANGED Loadouts to fit all objects

Atlas fixes

---

cba_settings.sqf
tools/build_settings_config.sh

Updated build and settings

---

tools/build.ini
tools/build.py

Fixed build script

---

cScripts/CavFnc/functions/systems/fn_addQuickSelectionList.sqf

Fixed atlas not being bravo

---

cScripts/Loadouts/script/CfgFunctions.hpp
cScripts/Loadouts/script/functions/main/fn_findLoadableWeapon.sqf
cScripts/Loadouts/script/functions/main/fn_getMagwellMagazines.sqf

- Fixed spawn with empty magazines loaded in the primary weapon.
- Added getMagwellMagazines function that returns array of compatible magazines.

fix spawn with empty magazine loaded - Mag Well system

---

cba_settings.sqf

Updated CBA settings

---

cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf

- ADDED: Ability to see if and what medic training level in the Information diary record.
- ADDED: Ability to see if and what engineer training level in the Information diary record.

Diary show if you are med or eng trained

---

.gitignore

Ignoring changes to debug

---

cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp

- CHANGED: Atlas medics how have 1 times m67
- CHANGED: "more will write later..."

Blake update to loadouts

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrate.sqf
cScripts/CavFnc/functions/systems/fn_addArsenal.sqf
cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp

- Added arsenal public blacklist
- Added public selection scale automatically applying public blacklist on public mission setting

Public arsenal blacklist

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/mission/fn_addHaloJump.sqf
cScripts/CavFnc/functions/mission/fn_addJump.sqf
cScripts/CavFnc/functions/systems/fn_addFortifyArea.sqf
cScripts/CavFnc/functions/systems/fn_checkVehicle.sqf
cScripts/CavFnc/functions/systems/fn_doHaloJump.sqf
cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf

- ADDED: Halo function
- CHANGED: Settings for jumping and fortify is saved in its object variable.
- ADDED: New Check Vehicle / Aircraft function with a new information text.

Added halo and new check vic function

---

cScripts/CavFnc/functions/systems/fn_deleteDroppedObjects.sqf

Junk will not be cleaned if more than 1 player near the crate.

Fix junk cleaner

---

cScripts/CavFnc/cScripts_postInit.sqf
cScripts/CavFnc/functions/players/fn_doPlayerAnnouncement.sqf

- ADDED: You are now greeted with your selected slot and squad name.

Improved announchments

---

init.sqf

- Added category to rpt log for init.sqf

init show log category

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/debug/fn_diag_dumpPlayer.sqf

- Added dump player data function

Added diagnostic function

---

cScripts/CavFnc/cScripts_postInit.sqf

Added fixed for delayed init

---

cScripts/CavFnc/functions/mission/fn_addGetOutHelo.sqf

- Fixed get out function script header

Fixed headers

---

cScripts/CavFnc/functions/documents/fn_Doc_Radio.sqf
cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf
cScripts/CavFnc/functions/players/fn_setActiveRadio.sqf

- Radio functions now check for acre before execution

added ACRE checks

---

tools/config_noLoadouts.json
tools/config_public.json

Fixed Pathing

---

.github/workflows/deploy.yml
tools/config_noLoadouts.json

More Deploy Fixes

---

tools/deploy.sh

Added noLoadout to deploy

---

cba_settings.sqf

Revert "Update cba_settings.sqf"

---

cScripts/CavFnc/functions/init/fn_initDocuments.sqf

- FIXED: Script error by delaying name check untill name exist

Delayed name check untill name exist

---

cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf

- Added ranger insignia to selector
Close #682

Added ranger insignia

---

cScripts/CavFnc/functions/gear/fn_gear_applyAbilities.sqf

- REMOVED: Removed immortality for zeus operators.

Removed depricated zeus immortality

---

cScripts/CavFnc/functions/gear/fn_gear_applyAbilities.sqf

- FIXED EOD being number instead of bool

EOD now use boolean instead of number

---

cScripts/CavFnc/functions/init/fn_initAI.sqf

- CHANGED Server now only set ai instead of all clients

Server only set ai

---

cScripts/CavFnc/functions/documents/fn_Doc_Radio.sqf
cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf

- ADDED: cScripts now set freequency for each channel of longrange

Cav Applied radio frequencies

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/CavFnc/functions/logistics/fn_doSupplyCrate.sqf

- CHANGED RHS Flares to ACE Flares
Fixes #673

Tf47 re add bro version

---

cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf

- FIXED: Error in setup_radios function

Fixed isplayer error

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf
cScripts/CavFnc/functions/mission/fn_addHaloJump.sqf
cScripts/CavFnc/functions/mission/fn_addLineJump.sqf
cScripts/CavFnc/functions/systems/fn_para_backpack.sqf
cScripts/CavFnc/functions/systems/fn_para_equipment.sqf
cScripts/CavFnc/functions/systems/fn_para_haloJump.sqf
cScripts/CavFnc/functions/systems/fn_para_lineJump.sqf

- CHANGED: Renamed all parachute functions and added para prefix to them
- FIXED: HALO Jump not functioning
- ADDED: Backpack on chest simulation
- FIXED: Minor documentation on jump functions
- CHANGED: Params utalizing better syntax
- CHANGED: Long range radios now have their labels back

Updated and fixed para system

---

cScripts/CavFnc/functions/systems/fn_addInsigniaSelectionList.sqf

- Add 1/A/1-7 patches
- Add 1/1/A/1-7 patches
close #704

added alpha patches

---

cScripts/CavFnc/cScripts_preInit.sqf

fixed setFortifyRestriction existing

---

cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf

- Fix name issue with para jump
- FUNC(addJump) -> EFUNC(para,lineJump)
- FUNC(addHaloJump) -> EFUNC(para,haloJump)

Para jump name fix

---

cScripts/CavFnc/functions/systems/fn_checkVehicle.sqf
cScripts/CavFnc/functions/systems/fn_para_backpack.sqf
cScripts/CavFnc/functions/systems/fn_setVehicleSettings.sqf

Fixed halo jump not working propperly

---

.github/workflows/deploy.yml
tools/deploy.sh

deploy changes

---

.github/workflows/deploy.yml

removed armake

---

cScripts/CfgLoadouts.hpp

Removed unused files

---

cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp

- FIXED: Classnames referencing non exising classnames

Fixed errored classnames

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/functions/documents/fn_Doc_Radio.sqf
cScripts/CavFnc/functions/gear/fn_gear_applyLoadout.sqf
cScripts/CavFnc/functions/gear/fn_gear_postInit.sqf
cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf
cScripts/CavFnc/functions/init/fn_initModulesZen.sqf
cScripts/CavFnc/functions/modules/fn_zenModuleResetPlayerRadio.sqf
cScripts/CavFnc/functions/systems/fn_clearRadioIds.sqf

- ADDED: clearRadioIds3
- ADDED: acre waits to wait for radio initzializations

Massive radio update

---

cScripts/CavFnc/functions/diag/fn_log.sqf
cScripts/CavFnc/functions/gear/fn_gear_applyLoadout.sqf

- Fixed system chat message being text instead of string
- Improved the gear aplication function

Log and loadout

---

Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe
Compositions/Cav_Misfit_Platoon_Deployment/header.sqe

- CHANGED: Replaced Bandit-4 and Misfit-4  with weapons team

Replaced Bandit 4 and Misfit 4

---

cScripts/CavFnc/functions/systems/fn_clearRadioIds.sqf

Fixed base radio not being added

---

cScripts/CavFnc/functions/gear/fn_gear_applyLoadout.sqf
cScripts/CavFnc/functions/init/fn_initStaging.sqf

- CHANGD: Rolledback some ACRE checks
- FIXED: Server trying to add stadging checks to it self

 Rollback som changes and removed stadgeing server

---

cScripts/CavFnc/functions/gear/fn_gear_applyLoadout.sqf
cScripts/CavFnc/functions/gear/fn_gear_postInit.sqf
cScripts/CavFnc/functions/gear/fn_gear_setupRadios.sqf
init.sqf

- CHANGED: Radio init now only handled in init.sqf

radioSetup now run only on init.sqf

---

cScripts/CavFnc/functions/systems/fn_clearRadioIds.sqf

- CHANGED: Clear Radio IDs nw also set your channels and active radio.

Clear Radio IDs nw also set your channels and active radio.

---

cScripts/CavFnc/functions/modules/fn_zenModuleCreateStarterCrate.sqf
cScripts/CavFnc/functions/modules/fn_zenModuleCreateSupplyCrate.sqf
cScripts/CavFnc/functions/systems/fn_addReGear.sqf

- CHANGED: Zen moduel seprated execution for supplies and only on server
- CHANGED: Utalizing ACE add to curator script
- CHANGED: Updated regear script to utalize same selection as everything else

Separated execution changed gear

---

cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/init/fn_initACELoadouts.sqf
cScripts/CavFnc/functions/players/fn_getPlayerName.sqf
cScripts/CavFnc/functions/players/fn_getPlayerRank.sqf
cScripts/CavFnc/functions/players/fn_setPlayerRank.sqf
cScripts/script_component.hpp

- CHANGED: Clan tag is now checked in cba settings
- REMOVED: `MAINCLANTAG` define

Clan tag changes

---

cScripts/CavFnc/functions/modules/fn_zenModuleCreateFieldHospital.sqf
cScripts/CavFnc/functions/modules/fn_zenModuleCreateMedicalCrate.sqf
cScripts/CavFnc/functions/modules/fn_zenModuleCreateStarterCrate.sqf
cScripts/CavFnc/functions/modules/fn_zenModuleCreateSupplyCrate.sqf
cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp

- REMOVED: Atlas Logistical loadouts.
- CHANGED: Merged Atlas Team Leader and Team Member loadout.
- FIXED: Typo causing logistical zeus crates not to provide inventory.

Crate atlas

---

cScripts/CavFnc/functions/logistics/fn_doStarterCrateSupplies.sqf

- REMOVED: All radios from crates

removed passive radios from crates

---

cScripts/CavFnc/CfgFunctions.hpp
cScripts/CavFnc/cScripts_preInit.sqf
cScripts/CavFnc/functions/init/fn_init_zenModuels.sqf
cScripts/Loadouts/CfgLoadouts_Charlie_Weapon.hpp

Fixed post merge issues

---

cScripts/cScripts_postInit.sqf
cScripts/cScripts_preInit.sqf

fixed path error

---

cScripts/cScripts_postInit.sqf
cScripts/cScripts_preInit.sqf
cScripts/functions/init/fn_init_staging.sqf
cScripts/functions/systems/fn_checkStagingZone.sqf
cScripts/functions/systems/fn_setupLoadoutCategories.sqf
cScripts/functions/vehicle/fn_vehicle_addRegearAction.sqf
cScripts/functions/vehicle/fn_vehicle_addRepairAction.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- ADDED: You can now define stadging zone via global variable

Staging var

---

cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- CHANGED: Broader usage of helicopter for inventory appications

Broader usage of helicopter for inventory appications

---

cScripts/CfgLoadouts.hpp
cScripts/Loadouts/CfgLoadouts_Alpha_Rotary.hpp
cScripts/Loadouts/CfgLoadouts_Bravo_Crew.hpp
cScripts/Loadouts/CfgLoadouts_Bravo_Leadership.hpp
cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp
cScripts/functions/players/fn_getCompanyVariable.sqf
cScripts/functions/systems/fn_getArsenalWhitelist.sqf
cScripts/functions/systems/fn_setupLoadoutCategories.sqf

- ADDED: Missing roles to viking units
- CHANGED: Inhetitence for viking classes
- FIXED: Bug were company variable always returned `none` causing arenal filter to return default company
- CHANGED: Arsenal medic gear is not added via ablility and not role
- ADDED: Missing launchers to weapons team and viking units
- ADDED: New medical equipment to Atlas
- CHANGED: 40mm grenades are now avalible for all loadouts and not just weapon system

Viking role fixes

---

cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
cScripts/Loadouts/CfgLoadouts_Charlie_Squad.hpp
cScripts/cScripts_postInit.sqf
cScripts/cScripts_preInit.sqf
cScripts/functions/init/fn_init_staging.sqf
cScripts/functions/init/fn_init_vehicle.sqf
cScripts/functions/mission/fn_addStagingZone.sqf
cScripts/functions/mission/fn_setVehicleLable.sqf
cScripts/functions/systems/fn_checkStagingZone.sqf
cScripts/functions/systems/fn_createVehicleLable.sqf
cScripts/functions/systems/fn_setupLoadoutCategories.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
cScripts/functions/vehicle/fn_vehicle_addRegearAction.sqf
cScripts/functions/vehicle/fn_vehicle_addRepairAction.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- CHANGED: Varrius improvments

Varius improvments

---

cScripts/cScripts_preInit.sqf
cScripts/functions/gear/fn_gear_getCurrentLoadout.sqf
cScripts/functions/systems/fn_addArsenal.sqf
cScripts/functions/systems/fn_addLoadoutSelection.sqf
cScripts/functions/systems/fn_checkStagingZone.sqf
cScripts/functions/systems/fn_getArsenalWhitelist.sqf
cScripts/functions/systems/fn_getUnitArsenalDefault.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Added setting and fixed numbering
- Improved check
- disabled arenal if you dont have any valid loadout
- Whitelist return empty
- ability to override company check
- Fixed function returning empty
- added ability to have empty inventory
- Disable default for non valid loadout

Quality of life and bugfixes

---

.github/workflows/testing.yml

Fixed sqf linter pathing

---

cScripts/functions/gear/fn_gear_setupRadios.sqf
cScripts/functions/players/fn_setActiveRadio.sqf
cScripts/functions/systems/fn_clearRadioIds.sqf
tools/config_noACRE.json

- ADDED: Additional acre checks
- ADDED: ACRE build

ACRE checks

---

tools/deploy.sh

added no acre build

---

.github/workflows/deploy.yml

added noacre deploy

---

cba_settings.sqf

- CHANGED: CBA Settings ACE View Distance Limiter is now enabled

Fixed ace diewing distance limiter

---

cScripts/CfgFunctions.hpp
cScripts/cScripts_preInit.sqf
cScripts/functions/init/fn_init_chatCommands.sqf
cScripts/functions/init/fn_init_eventHandlers.sqf
cScripts/functions/modules/fn_zenModule_callEndex.sqf
cScripts/functions/systems/fn_getAttendance.sqf

- ADDED: #attendance chat command
- CHANGED: get attendance is now a local event

New attendance system

---

cScripts/functions/logistics/fn_doStarterCrate.sqf

- FIXED: Stageing Starter Crate parameter not working

fixed _hasStagingZone boolean

---

cScripts/CfgFunctions.hpp
cScripts/functions/systems/fn_training_addHitIndicator.sqf
cScripts/functions/systems/fn_training_clearhitIndicator.sqf

- ADDED: Target script that allow you to see where you hit a object

Added target indicator allow you to see where you hit a object

---

Compositions/Cav_ATLAS_Attachment/composition.sqe
Compositions/Cav_ATLAS_Attachment/header.sqe
Compositions/Cav_Alpha_Company/composition.sqe
Compositions/Cav_Alpha_Company/header.sqe
Compositions/Cav_BANDIT_Platoon/composition.sqe
Compositions/Cav_BANDIT_Platoon/header.sqe
Compositions/Cav_MISFIT_Platoon/composition.sqe
Compositions/Cav_MISFIT_Platoon/header.sqe
Compositions/Cav_S3_Staff/composition.sqe
Compositions/Cav_S3_Staff/header.sqe
Compositions/Cav_SABER_Platoon/composition.sqe
Compositions/Cav_SABER_Platoon/header.sqe
Compositions/Cav_VIKING_Platoon/composition.sqe
Compositions/Cav_VIKING_Platoon/header.sqe
cScripts/functions/modules/fn_zenModule_setDamage.sqf

- Fixed headers
Related to this commit; https://github.com/7Cav/cScripts/commit/1c7a6ee0ab86572b72ad10d503a8ecb25e6ddb7f

Updated headers

---

tools/sqf_linter.py
tools/sqf_validator.py

updated tools

---

cScripts/CfgFunctions.hpp
cScripts/functions/vehicle/fn_vehicle_getPylon.sqf

- Added loadout file for vehciles

Added getPylon function

---

cScripts/CfgFunctions.hpp
cScripts/functions/init/fn_init_vehicle.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addRegearAction.sqf
cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- CHANGED: Abrams now spawn with mixed loadout.
- ADDED: Loadouts are now save in the vehicle variable.
- CHANGED: adding loadouts are now handled by `vehicle_applyLoadout ` function.

Vehicle loadout spawn

---

Compositions/Cav_ATLAS_Attachment/composition.sqe
Compositions/Cav_ATLAS_Attachment/header.sqe
Compositions/Cav_Alpha_Company/composition.sqe
Compositions/Cav_Alpha_Company/header.sqe
Compositions/Cav_BANDIT_Platoon/composition.sqe
Compositions/Cav_BANDIT_Platoon/header.sqe
Compositions/Cav_MISFIT_Platoon/composition.sqe
Compositions/Cav_MISFIT_Platoon/header.sqe
Compositions/Cav_S3_Staff/composition.sqe
Compositions/Cav_S3_Staff/header.sqe
Compositions/Cav_SABER_Platoon/composition.sqe
Compositions/Cav_SABER_Platoon/header.sqe
Compositions/Cav_VIKING_Platoon/composition.sqe
Compositions/Cav_VIKING_Platoon/header.sqe

Fixed headers again

---

cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- Changed: GetPylon now don't need vehicle object cause it made no sense

Remove Vehicle check for getPylon

---

cScripts/functions/systems/fn_para_equipment.sqf
cScripts/functions/systems/fn_para_haloJump.sqf

- Added: Ability to ignore NVG drop when jumping
- Changed: HALO jump now keep your nods

Added ability to ignore NVG drop

---

description.ext

Added debugging personal

---

cScripts/functions/systems/fn_addInsigniaSelectionList.sqf

- ADDED 1/B/1-7 Insignia
- ADDED 4/1/B/1-7 Insignia

added missing insignias

---

cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf

- Fixed faction system not implemented in cosmetics causing code to bleedover to non valid factions.

Fixed faction system not implemented in cosmetics

---

cScripts/functions/systems/fn_addArsenal.sqf

- CHANGED: Arsenal box are removed globaly from player on destruction

remove arsenal box globaly from player

---

cScripts/CfgFunctions.hpp
cScripts/functions/init/fn_init_zenModuels.sqf
cScripts/functions/modules/fn_zenModule_stagingZones.sqf
cScripts/functions/systems/fn_checkStagingZone.sqf

- Added ability to disable stageing zone via module

Added ability to disable stageing zone via module

---

cScripts/cScripts_preInit.sqf

- CHANGES: Default grenade to be the vanilla

Change default grenade to mirror changes to gear

---

cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf

- Added jumps to USAF vehicles

Added jump functions to USAF airframes

---

cScripts/CfgFunctions.hpp
cScripts/functions/testing/fn_testing_loadoutArrays.sqf

- Added a testing function to check loadouts

Added a testing function

---

cScripts/functions/systems/fn_checkStagingZone.sqf

Added false return if there are no zones nearby

Added false return if there are no zones nearby stagezone check 

---

cScripts/functions/gear/fn_gear_applyLoadout.sqf
cScripts/functions/gear/fn_gear_saveLoadout.sqf
cScripts/functions/helpers/fn_exportLoadoutToArsenal.sqf

- Change loadout system to usage of CBA extended loadout array (this is backwards compatible)

Change to usage of CBA loadout array

---

cScripts/functions/init/fn_init_zenModuels.sqf
cScripts/functions/modules/fn_zenModule_callEndex.sqf
cScripts/functions/systems/fn_getAttendance.sqf

- Removed missleading clipboard feature and text due to not working in MP

Removed missleading clipboard feature due to not working in MP

---

cScripts/cScripts_preInit.sqf
cScripts/functions/init/fn_init_staging.sqf
cScripts/functions/logistics/fn_doStarterCrate.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf

- Added cba toggle for staging system

Added cba toggle for staging system

---

cScripts/CfgFunctions.hpp
cScripts/functions/mission/fn_addBaseCrate.sqf

- Added addBaseCrate function (quick function for starterCrate)

Added base crate function (quick function for starterCrate)

---

cScripts/functions/diag/fn_log.sqf

- Fixed send to server if you are server

Don't send to server if you are server

---

cScripts/Loadouts/CfgLoadouts_Charlie_Weapon.hpp

- Added Fireteam Classname to loadouts

Added Fireteam Classname to loadouts

---

cScripts/functions/gear/fn_gear_applyLoadout.sqf
cScripts/functions/gear/fn_gear_selectLoadout.sqf
cScripts/functions/logistics/fn_doStarterCrate.sqf
cScripts/functions/mission/fn_addBaseCrate.sqf
cScripts/functions/mission/fn_addStagingZone.sqf
cScripts/functions/mission/fn_setVehicleLable.sqf
cScripts/functions/modules/fn_zenModule_stagingZones.sqf
cScripts/functions/systems/fn_addArsenal.sqf
cScripts/functions/systems/fn_addInsigniaSelectionList.sqf
cScripts/functions/systems/fn_getIcon.sqf
cScripts/functions/systems/fn_setupLoadoutSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addRadio.sqf

- Added cavAddon missing insignias
- Allow no icon on loadouts or empty string
- Fixed baseCreate exection on non server clients
- Fixed documentation
- Fixed dubble import of include
- Fixed issue were startercreates did not create staging zones
- Removed debugging
- Removed unused classnames
Thx SPC.Bethea.A for finding some of them

Varrius fixes230514

---

cScripts/functions/systems/fn_addInsigniaSelectionList.sqf

- Fixed missing insignia texture

Fixed missing insignia texture

---

cScripts/functions/logistics/fn_checkItemValidity.sqf

Updated validity item check 

---

cScripts/functions/systems/fn_addInsigniaSelectionList.sqf

- Fixed S3 insignia being wrongly referenced

Fixed S3 insignia being wrongly referenced

---

cScripts/functions/mission/fn_addLoadoutAction.sqf

Fixed grab loadout not accepting loadout array
Fixed parameter check loadout not being checked.

Fixed bug with check and array not being avalible

---

cScripts/functions/systems/fn_getArsenalWhitelist.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf

- Fixed variable and fixed dubble quote

Fixed variable and fixed dubble quote

---

cScripts/Loadouts/CfgLoadouts_Alpha.hpp
cScripts/Loadouts/CfgLoadouts_Alpha_FixedWing.hpp
cScripts/Loadouts/CfgLoadouts_Alpha_Rotary.hpp
cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp
cScripts/Loadouts/CfgLoadouts_Bravo_Crew.hpp
cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
cScripts/Loadouts/CfgLoadouts_Charlie_Squad.hpp
cScripts/Loadouts/CfgLoadouts_Charlie_Weapon.hpp
cScripts/Loadouts/CfgLoadouts_Common.hpp
cScripts/Loadouts/CfgLoadouts_UserCustom.hpp

- Fixed warning for bad class colon

Fixed warning for bad class colon

---

tools/config_style_checker.py
tools/search_privates.py
tools/search_undefinedFunctions.py

updated script

---

cScripts/CfgFunctions.hpp
cScripts/cScripts_preInit.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_applyTextures.sqf
cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- Add a function to quickly apply textures in sequence to a vehicle.
- Add Pandur II to the vehicle staging arsenal system.

Stryker dragoon customization

---

cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf

- Change the decal placed on the medical vehicle upon vehicle init.

Changed default decal on the medical vehicles

---

Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
Compositions/Cav_Fixed_Wing_Aviation/composition.sqe
Compositions/Cav_Fixed_Wing_Aviation/header.sqe
Compositions/Cav_JTAC_Addon/composition.sqe
Compositions/Cav_JTAC_Addon/header.sqe
Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe
Compositions/Cav_Misfit_Platoon_Deployment/header.sqe
Compositions/Cav_Rotary_Aviation/composition.sqe
Compositions/Cav_Rotary_Aviation/header.sqe
Compositions/Cav_S3_Mission_Controller/composition.sqe
Compositions/Cav_S3_Mission_Controller/header.sqe
Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe

Updated all the compositions:
- Fixed all the inits for all the units due to an Arsenal bug and Callsigns not displaying correctly.
- Fixed the Slotting list and how its displayed.
- Fixed all the Zeus modules.
- Added Respawn module back so it works with cScripts.
- Added Editable objects back and linked it to Game Master and Zeus so everything is loaded for all the Mission controllers.
- Added Medical script for ATLAS vehicles provided by Turn/Brostrom.

Updated compositions

---

Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe

Revert "Stryker Dragoon Temp Composition"

---

Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe

Updated the vehicles from old humvees to SOCOM humvees. These can carry more people and are most used by the Platoons.

Charlie-Compositons-Vehicle-Updated

---

Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe
cScripts/functions/logistics/fn_doSupplyCrate.sqf

- Updated Supply Crate 
- Consolidated AT4's into HEDP.
- Consolidated 40mm HET and HEDP into HEDP
- Replaced the RHS M67 Handgrenade with ACE/Vanilla M67 Handgrenade.
- decreased overall amount of 60MM mortar AMMO.
- Decreased amount of Flashbangs, Flares, and Chemlights.
- Decreased earplugs from 25 to 3.
- Decreased TQ's from 36 to 15.
- Removed Green Smoke
- Removed IR grenade
- Removed personal aid kits,
- Removed Backpacks

Update fn do supply crate.sqf

---

Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe

- Replace Viking Platoon Strykers with Pandur II APCs
- Update Alpha and Bravo Grenadier to Scouts
- Update Alpha and Bravo Automatic Rifleman to Machine Gunners
#900

Stryker Dragoon Temp Composition

---

Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe

- Correct Viking slotting order
- Set strykers in Viking composition as medical vehicles

Fix viking slot order

---

Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe

- Update atlas vehicles of composition.
- Update slotting order of composition.

Update slotting order and composition

---

cScripts/functions/testing/fn_testing_loadoutArrays.sqf

- Added check to check for array maulformation

Added check to check for array maulformation

---

cScripts/functions/logistics/fn_checkItemValidity.sqf

- Removes classnames of items in ACE Pharmacy mod from filter function fn_checkItemValidity

Removed items in ACE Pharmacy from fn_checkItemValidity

---

cScripts/cScripts_preInit.sqf

- Adds USAF to faction list to allow for static line jumps from that USAF mod aircraft
#926

Add USAF to faction list

---

cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf

- Make spawned vehicles that receive medical crates and inventories ace medical vehicles

Set vehicles that have medical inventories as ACE medical vehicles

---

Compositions/Cav_JTAC_Addon/composition.sqe

Changed Callsign from INFIDEL to CHAOS on Battalions request.

Changed Callsign from INFIDEL to CHAOS

---

cScripts/CfgFunctions.hpp
cScripts/functions/init/fn_init_vehicle.sqf
cScripts/functions/systems/fn_isValidFaction.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- Added faction check to missing functions
- Added Server checks

Fixed issues with functions, crates and cosmetics not working on Zeus spawned vehicles.

---

cScripts/functions/logistics/fn_createCargoCrate.sqf

- Improved create cargo crate code quality

Improved create cargo crate code quality

---

cScripts/CfgFunctions.hpp
cScripts/functions/logistics/fn_createCargoCrate.sqf
cScripts/functions/systems/fn_renameObject.sqf

- Added ability to change crate name

Added ability to rename crate

---

cScripts/functions/logistics/fn_createCargoCrate.sqf

Missing then added

---

cScripts/functions/modules/fn_zenModule_createMedicalCrate.sqf

- Fixed med crate module not spawning crate by using remote execution of create cargo crate

Changed medical crate module to use remote execution

---

.github/workflows/deploy.yml

Update build scripts

---

cScripts/cScripts_preInit.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- Removed texture application for Pandur and Pandur child classes.
- Removed ability to change texture for Pandurs in staging area.
- Added ability for Pandur children to toggle camo net in staging area.
- Removed ability for unarmed Dragoons to select pylons.

Added Stryker Dragoon compatibility

---

cScripts/functions/modules/fn_zenModule_callEndex.sqf
cScripts/functions/players/fn_getPlayerRank.sqf
cScripts/functions/players/fn_setPlayerRank.sqf
cScripts/functions/players/fn_setTeamColor.sqf

- Cleaned up and fixed formating and naming

Cleaned up and fixed formating and naming

---

cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addFlagAction.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf

- Made vehicle variables globaly broadcasted

Made vehicle variables globaly broadcasted

---

cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf

- Fixed arrays with trailing commas

Fixed arrays with trailing commas

---

cScripts/functions/logistics/fn_checkItemValidity.sqf

- Improved the filter function to do check per one item using a local function

Improved the item filter function

---

Compositions/Cav_Fixed_Wing_Aviation/composition.sqe
Compositions/Cav_Rotary_Aviation/composition.sqe

- Fixed the slotting order for all the groups to be displayed in the correct order when compositions are placed down.
- Fixed the missing basic engineer permissions for pilots/crew.

Updated Alpha Compositions

---

Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe

Added Stryker Dragoon for Viking and Medical Stryker for Atlas units.

Updated Bravo Compositions

---

Compositions/Cav_JTAC_Addon/composition.sqe
Compositions/Cav_JTAC_Addon/header.sqe

Changed TACP/FAC Callsigns
- INFIDEL is now CHAOS
- PEGASUS is now VANQUISH

Updated TACP/FAC Callsigns

---

cba_settings.sqf

- Updated CBA Settings to match current state
does not have TFAR

Updated CBA Settings to match current state

---

cScripts/functions/mission/fn_gate.sqf
cScripts/functions/mission/fn_teleport.sqf

- Depricated gate function
- Depricated teleport function

Depricated scripts for cav scripts instead

---

cScripts/cScripts_preInit.sqf
cScripts/functions/init/fn_init_aceItemReplace.sqf

- Added magazine replacement system to sets a preference to sertain mod (Perfer RHS then ACE or ACE then RHS)

Added magazine replacement system to sets a preference to sertain mod

---

cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Swap M252 with Mk6 mortar in Viking-4 Stryker, add laser guided shells.

Swap M252 with Mk6, add laser guided ammo

---

cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf

- Added variable to stop application localy for clients

Added variable to stop adding of additional staging actions localy for clients

---

cScripts/functions/init/fn_init_vehicle.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_reset.sqf

- Placed vehicles now clear ace cargo before adding new equipment.
- Vehicle reset function fully implemented.
- Duplicated staging actions error fixed
- Vehicles spawned in zeus now have the same functionality as those spawned in 3Den

Fixed bug where zeus-placed vehicles were not properly initialized

---

cScripts/CfgLoadouts.hpp
cScripts/Loadouts/CfgLoadouts_Training.hpp
cScripts/functions/systems/fn_setupLoadoutCategories.sqf

- Added loadouts for training units

Added loadouts for training units

---

cScripts/Loadouts/CfgLoadouts_Training.hpp
cScripts/functions/init/fn_init_eventHandlers.sqf
cScripts/functions/init/fn_init_logistics.sqf
cScripts/functions/init/fn_init_skillAdjustment.sqf
cScripts/functions/init/fn_init_vehicle.sqf
cScripts/functions/logistics/fn_createCargoCrate.sqf
cScripts/functions/logistics/fn_doStarterCrateSupplies.sqf
cScripts/functions/logistics/fn_setCargoAttributes.sqf
cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf
cScripts/script_component.hpp

- Better format for if not
- Better logging and warning instead of error in create cargo crate function
- Disabled global debugging
- Fixed errors in logistical database
- Fixed missing : in case for the startercrate
- Fixed missing icon for training loadout
- Updated and adjusted vehicle so pylon and default actually gets applied.
- Removed the clear actions for zeus spawned items we dotn want them to be removed only added if missing.

Mayor fixes and adjustments

---

cScripts/CfgFunctions.hpp
cScripts/functions/init/fn_init_logistics.sqf
cScripts/functions/init/fn_init_vehicle.sqf
cScripts/functions/logistics/fn_createCargoCrate.sqf
cScripts/functions/systems/fn_renameObject.sqf
cScripts/functions/testing/fn_testing_equipmentUsed.sqf
cScripts/functions/testing/fn_testing_loadoutArrays.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf

- Fixed bugs and faulty equipment as well as vehicle init delay

Fixed bugs and faulty equipment as well as vehicle init delay

---

cScripts/functions/init/fn_init_vehicle.sqf
cScripts/script_component.hpp

- Added Turns fix for curator spawned vehicles not getting items

Added Turns fix for curator spawned vehicles not getting items

---

cScripts/functions/init/fn_init_logistics.sqf

- Fixed wrong phenylephrine class name

Fixed: wrong phenylephrine class name

---

cScripts/functions/gear/fn_gear_applyAbilities.sqf

- Fixed Typo in ability function removing the ability localy and added it globaly

Fixed Typo in ability function removing the ability localy

---

cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Fixed duplicate removal of ace items moved container getter to a variable

Fixed duplicate removal of ace items moved container getter to a variable

---

cScripts/functions/init/fn_init_vehicle.sqf

- Fixed function not getting added and added check for added already

Fixed function not getting added and added check for added already

---

cScripts/functions/init/fn_init_vehicle.sqf

- Gets not sets like a silly goose

Get variable not set variable for zeus addons

---

cScripts/Loadouts/CfgLoadouts_Bravo_Atlas.hpp

- Changed atlas loadouts to be medic role as well as moved to top baseclass

Changed atlas loadouts to be medic role as well as moved to top baseclass

---

.github/workflows/deploy.yml

Update deploy.yml test

---

.github/workflows/deploy.yml

deploy fixes

---

.github/workflows/deploy.yml

Fixed steps

---

.github/workflows/deploy.yml
.github/workflows/deploy_main.yml

added main deploy

---

.github/workflows/deploy_main.yml

adnd again

---

.github/workflows/deploy.yml
.github/workflows/deploy_main.yml

Deploy fix again

---

.github/workflows/deploy.yml

Fixed deploy

---

.github/workflows/deploy_artifacts_main.yml
.github/workflows/deploy_artifacts_tag.yml

Adjusted deployment

---

cba_settings.sqf

- Enabled ace_zeus_autoAddObjects for all clients

Enabled ace_zeus_autoAddObjects for all clients

---

cba_settings.sqf

- Let people change the phosphor color of their NVG lens.
- Apparently people REALLY like white phosphors

Make Fawk's NVG mod options optional

---

.github/workflows/testing.yml
cScripts/CfgFunctions.hpp
cScripts/cScripts_preInit.sqf
cScripts/functions/gear/fn_gear_postInit.sqf
cScripts/functions/init/fn_init_eventHandlers.sqf
cScripts/functions/init/fn_init_vehicle.sqf
cScripts/functions/logistics/fn_addCargo.sqf
cScripts/functions/logistics/fn_createCargoCrate.sqf
cScripts/functions/logistics/fn_doSupplyCrate.sqf
cScripts/functions/mission/fn_addGetOutHelo.sqf
cScripts/functions/mission/fn_addHaloJump.sqf
cScripts/functions/mission/fn_addLineJump.sqf
cScripts/functions/players/fn_setRadioChannel.sqf
cScripts/functions/systems/fn_clearRadioIds.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctionsGlobal.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
description.ext
init.sqf
tools/checkDebug.sh
tools/checkFixme.sh
tools/checkLogging.sh

- Updated CI scripts testing now lock merge for DEBUG, FIXME and wrong LOGGING usage (Usefull for development)
- Fixed issues with zeus created objects not getting functions inventory added propperly
- Fixed GetOut and Jump scripts not geting applied
- Cleared the CBA_Setting and debug whitelist
- Moved radio setup back to gear post init.
- Disabled RHS decal adding on JIP vehicles
Close #1005
Close #989

Fixed init issues with scripts as well as persistent adding of scripts and functionalities

---

cScripts/functions/logistics/fn_checkItemValidity.sqf

- Removed ACRE and TFAR radios in the ItemValidity
Its already handled byt the config check

Removed ACRE and TFAR radios in the ItemValidity

---

cba_settings.sqf

- Updated the CBA to contain the Tac R TFAR channel settings.

Added tfar auto join channel settings

---

.github/workflows/pull_request.yml

added wip lable test to block merge on wip tag

---

cScripts/functions/init/fn_init_logistics.sqf
cScripts/functions/testing/fn_testing_loadoutArrays.sqf

- Unit tests and database now use isEqualType instead of typeName

Unit tests and database now use isEqualType instead of typeName

---

cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Disabled renaming of cargo possible vehicles globaly

Disabled renaming of cargo possible vehicles globaly

---

cScripts/cScripts_preInit.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf

- Disabled decals propperly globaly per vehicle

Disabled decals propperly globaly per vehicle

---

cScripts/functions/mission/fn_addEscapeWreck.sqf
cScripts/functions/mission/fn_addGetOutHelo.sqf
cScripts/functions/mission/fn_addHaloJump.sqf
cScripts/functions/mission/fn_addLineJump.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctionsGlobal.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_reset.sqf

- Updated variable name to let you know its duplication blockers

Updated variable name to let you know its duplication blockers

---

cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmetics.sqf
cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_addFlagAction.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctionsGlobal.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf
cScripts/functions/vehicle/fn_vehicle_addPylonSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addRadio.sqf
cScripts/functions/vehicle/fn_vehicle_addRegearAction.sqf
cScripts/functions/vehicle/fn_vehicle_addRepairAction.sqf
cScripts/functions/vehicle/fn_vehicle_addStagingActions.sqf
cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_applyTextures.sqf
cScripts/functions/vehicle/fn_vehicle_getPylon.sqf
cScripts/functions/vehicle/fn_vehicle_reset.sqf
cScripts/functions/vehicle/fn_vehicle_setRadio.sqf
cScripts/functions/vehicle/fn_vehicle_setupPylonCategories.sqf

- Removed forced server application on vehicle_addCosmetics
- Updated script headers on all vehicle functions.
- Minor format fixes

Updated script header some minor fixes

---

cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addFunctionsGlobal.sqf

- Added FRIES to RHS UH60 
- Added FRIES to VTX MH60M

Equiped RHS UH60 and VTX MH60M with FRIES

---

cScripts/functions/init/fn_init_logistics.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Added ropes to helicopters
***Note:** they are only added if required*

Added ropes to helicopters

---

Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe

Charlie MAAWS team had incorrect base units so they didn't spawn with the correct gear.
Replaced the Rifleman and CLS base unit which was being used to the correct MAAWS units so they spawned with the correct gear.

Fixed Charlie Weapons Squad MAAWS Team

---

cScripts/functions/gear/fn_gear_applyLoadout.sqf

Then they fixed the then
- Fixed missing then

Fixed missing then

---

Compositions/Cav_Bandit_Platoon_Deployment/composition.sqe
Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
Compositions/Cav_Misfit_Platoon_Deployment/composition.sqe
Compositions/Cav_Misfit_Platoon_Deployment/header.sqe
Compositions/Cav_Stryker_Scout_Platoon/composition.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe

- Updated the compositions to get rid of dependancies of the old ACE mods.
- Fixed the missing INIT lines on the Bandit-4 MAAWS gunner.

Fixed MAAWS for Bandit-4 and revived redundant mod dependencies 

---

.github/workflows/testing.yml
tools/checkPullRequestTitle.sh

Added CI for pull request title

---

tools/checkPullRequestTitle.sh

Fixed spelling in CI test

---

cScripts/Loadouts/CfgLoadouts_Special.hpp

- Fixed issues were loadout and unit were pased to the unit variable on S3 loadouts.

Fixed issues were loadout and unit were pased to the unit variable on S3 loadouts.

---

cScripts/Loadouts/CfgLoadouts_Special.hpp
cScripts/functions/vehicle/fn_vehicle_addDefaultLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_getPylon.sqf

- Fixed errors in getPylon
- Fixed errors in addDefaultLoadouts
- Fixed error in zeus loadout

Fixed various script errors

---

cScripts/CfgFunctions.hpp
cScripts/functions/logistics/fn_addCargo.sqf
cScripts/functions/logistics/fn_checkItemValidity.sqf
cScripts/functions/logistics/fn_logistics_getAllContainerItems.sqf
cScripts/functions/logistics/fn_logistics_getContainer.sqf

- Added improvements to the logistics container code

Added new getAllContainerItems function and improved documentation

---

cScripts/functions/gear/fn_gear_applyLoadout.sqf
cScripts/functions/init/fn_init_eventHandlers.sqf

- Fixed introduced bug and added better logging

Added better logging and cleaned up code

---

cScripts/functions/mission/fn_addStagingZone.sqf

- Fixed missing semicolon on staging variable
- Made zones transparent with outlince circle

Fixed missing semicolon on staging variable

---

cba_settings.sqf

ace_repair_patchWheelRequiredItems = ["ace_repair_anyToolKit"];
ace_medical_treatment_maxLitterObjects = 50;
ace_casings_maxCasings = 100;
ace_repair_repairDamageThreshold = 0.3;
ace_repair_repairDamageThreshold_engineer = 0.1;

Fixed Settings Errors maxLitterObjects, patchWheelRequiredItem, maxCasings, Fixed the repair settings

---

tools/checkPullRequestTitle.sh

- Added missing improved descriptor to check script

Added missing improved descriptor to check script

---

tools/checkPullRequestTitle.sh

- Added changed to accepted descriptor list

Added changed to accepted descriptor list

---

cScripts/functions/modules/fn_zenModule_createSupplyCrate.sqf

- Changed supply crate to a smaller one for zeus module spawn

Changed supply crate to a smaller one for zeus module spawn

---

.github/workflows/create_artifacts.yml
.github/workflows/deploy_artifacts_main.yml
.github/workflows/deploy_artifacts_tag.yml

- Changed and reverterd to deploy

Changed and reverterd to deploy

---

tools/checkPullRequestTitle.sh

- Improved and updated pull request test script

Improved and updated pull request test script

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Fixed issues with the bug report tempalte

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Fixed help text for bug template

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Added more version variants

---

.github/ISSUE_TEMPLATE/feature_request.md

Updated feature request template

---

tools/checkPullRequestTitle.sh

Updated the pull request check script

---

tools/deploy.sh

Updated deployment script

---

cScripts/CfgFunctions.hpp
cScripts/functions/gear/fn_gear_getLoadoutName.sqf
cScripts/functions/gear/fn_gear_postInit.sqf
cScripts/functions/init/fn_init_zenModuels.sqf
cScripts/functions/modules/fn_zenModule_applyLoadout.sqf
cScripts/functions/modules/fn_zenModule_regearTrooper.sqf

- Added ability for zeus to force a loadout on to a player
- Fixed type in function refersing player instead of _unit

Added ability for zeus to force a loadout on to a player

---

cScripts/functions/gear/fn_gear_postInit.sqf
tools/deploy.sh

- Fixed regear not working if you did not have a saved loadout

Fixed regear not working if you did not have a saved loadout

---

Compositions/Cav_Bandit_Platoon_Deployment/header.sqe
Compositions/Cav_Fixed_Wing_Aviation/header.sqe
Compositions/Cav_JTAC_Addon/header.sqe
Compositions/Cav_Misfit_Platoon_Deployment/header.sqe
Compositions/Cav_Rotary_Aviation/header.sqe
Compositions/Cav_S3_Mission_Controller/header.sqe
Compositions/Cav_Stryker_Scout_Platoon/header.sqe
Compositions/TacR_Public_Deployment/header.sqe

Updated deployment headers

---

cScripts/functions/init/fn_init_staging.sqf
cScripts/functions/mission/fn_addBaseCrate.sqf
cScripts/functions/mission/fn_doStarterCrate.sqf
cScripts/functions/modules/fn_zenModule_createStarterCrate.sqf
cScripts/functions/systems/fn_addLoadoutSelection.sqf
cScripts/functions/systems/fn_allowLoadout.sqf
cScripts/functions/systems/fn_setupLoadoutCategories.sqf
cScripts/functions/systems/fn_setupLoadoutSelection.sqf

- Fixed and improved staging and loadout selection process

Fixed and improved staging and loadout selection process

---

cScripts/functions/init/fn_init_aceArsenal.sqf
cScripts/functions/systems/fn_addArsenal.sqf

- Removed proxy event handler to prevent removal of Arsenal not being run

Changed how arsenal add and removal is handled to avoid action being added to players

---

cScripts/functions/gear/fn_gear_applyCosmetics.sqf
cScripts/functions/init/fn_init_aceArsenal.sqf
cScripts/functions/players/fn_profile_loadInsignia.sqf
cScripts/functions/players/fn_profile_saveInsignia.sqf
cScripts/functions/players/fn_unit_setInsignia.sqf

- Fixed insignia selection and save system being broken

Fixed insignia selection and save system being broken

---

.github/workflows/testing.yml
tools/checkTodo.sh

- Added todo check script this is a valid error. Its just to get them listed

Added todo check script this is a valid error. Its just to get them listed

---

tools/checkTodo.sh

Changed Todo to now exit 0 always

---

cScripts/functions/init/fn_init_logistics.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Add M240B and optic to Stryker kits
- Add crate with Stinger MANPAD to Stryker
- Remove AT4s and M32s

Added stinger crate and updated Stryker inventories

---

cba_settings.sqf

- Disabled Advanced Fatigue in the CBA settings

Fixed Disable Advanced Fatigue

---

cScripts/functions/init/fn_init_staging.sqf

- Added support of usage of better name "cscripts_staging_zone" instead of "zone_staging" (Both work)

Added support of usage of better name "cScripts_Staging_Zone" instead of "zone_staging"

---

Compositions/Cav_Rotary_Aviation/composition.sqe

- Fixed composition unit being player instead of playable

Fixed composition unit being player instead of playable

---

tools/checkPullRequestTitle.sh

Added Adjusted to pr name script

---

cba_settings.sqf

- The SOP for Charlie is to not have an artillery computer on the 60mm Mortar to force the team do to the calculations via rangetable and map tools.

Updated CBA_Settings to Disabled Artillery Computer

---

tools/checkPullRequestTitle.sh

Added disable and enabled to allowed pr title

---

cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Add the MH-47G to the vehicle category in anticipation of the modpack update in April.

Added MH-47G to vehicles module

---

cScripts/functions/init/fn_init_logistics.sqf

- Remove laser guided rounds and update Viking-4 81mm mortar to RHS M252.

Removed laser guided rounds and updated Viking-4 81mm mortar to RHS M252

---

Compositions/6.Cav_Rotary_Aviation/composition.sqe
Compositions/6.Cav_Rotary_Aviation/header.sqe
Compositions/7.Cav_Fixed_Wing_Aviation/composition.sqe
Compositions/7.Cav_Fixed_Wing_Aviation/header.sqe

Added:
- 2x MH-47G Grizzly's with Crews to the Rotary Compostion.
- Added the new F/A-18 and EAGLE crews.

Updated Alpha compositons with the new airframes

---

cScripts/initSettings.inc.sqf

- Fixed issues were all loadouts as well as the arsenal being unfiltered

Fixed issues were all loadouts as well as the arsenal being unfiltered

---

Compositions/1.Cav_Viking_Platoon/composition.sqe
Compositions/2.Cav_Bandit_Platoon/composition.sqe
Compositions/3.Cav_Misfit_Platoon/composition.sqe
Compositions/4.ATLAS_Platoon/composition.sqe
Compositions/6.Cav_Rotary_Aviation/composition.sqe
Compositions/7.Cav_Fixed_Wing_Aviation/composition.sqe

Stagning zones are now limited to the company the unit belongs to so people cannot pick alpha loadout as a charlie or viking infantry to gain equipment that is restricted and vica versa.

Updated staging zone boxes to limit Staging zone loadouts to Company

---

Compositions/6.Cav_Rotary_Aviation/composition.sqe

Updated the Alpha composition MH-47G to the MH-47G Easy Action with Rear guns after testing done on WFW and on request from rotary.

Updated MH-47G to the Easy Action version

---

cScripts/functions/vehicle/fn_vehicle_addFunctions.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

Fixed missing quotes in fn_vehicle_addInventory

---

cScripts/functions/init/fn_init_logistics.sqf

- Fix classnames for pistol flashlights

Fixed classnames for pistol flashlights

---

cScripts/functions/init/fn_init_message.sqf

- Changed check to check for lower then 2 then warn
- Changed message so it uses the log function.

Fixed missions now allow to have custom difficulty as well as veteran

---

cScripts/functions/systems/fn_addArsenal.sqf
cScripts/functions/systems/fn_getArsenalWhitelist.sqf

- Added a fallback creation of arsenal when arsenal is not created initzialy.
The fallback keeps the arsenal more stable then if it was created each time as it was.

Added fallback recreate for the arsenal when it is not initzialy created

---

cScripts/functions/init/fn_init_logistics.sqf
cScripts/functions/vehicle/fn_vehicle_addInventory.sqf

- Add signal grenades to Atlas
- Update 60mm mortar for Viking
- Update ammo counts for mortar
- Add M240 with sight already on gun
- Make sure cTab inventory items available for Charlie at appropriate levels
- Remove mortar tubes from Bravo arsenal

Updated Stryker Inventory and Arsenal

---

cScripts/Loadouts/CfgLoadouts_Bravo_Viking.hpp
cScripts/Loadouts/CfgLoadouts_Charlie_Squad.hpp
cScripts/functions/init/fn_init_logistics.sqf
cScripts/functions/systems/fn_getArsenalWhitelist.sqf

- Add role for stryker crew giving them long range radios.
-  Fix Charlie DMR loadout to remove medical insignia.

Added role for stryker crew and fixed Charlie DMR loadout

---

cScripts/functions/mission/fn_addHaloJump.sqf
cScripts/functions/mission/fn_addLineJump.sqf

- Spliced the doors and ramps to its own multiline code block to make easier to be read.
- Added the TF373_RAF_HC5 ramps to Halo jump as well.

Improved code quality for the the Halo and Line Jump script

---

cScripts/functions/init/fn_init_zenModuels.sqf

- Fixed missing code in Take attendance

Fixed Take Attendance zen moduel not working

---

.github/workflows/testing.yml

- Added better check for test only running once

Added better check for test only running once

---

.editorconfig

Updated editor config

---

cScripts/cScripts_postInit.sqf
cScripts/functions/init/fn_init_eventHandlers.sqf
cScripts/functions/systems/fn_getAttendance.sqf

- Changed attendance functions and module not return a copy pastable dialogue.
#1202

Changed attendance functions and module not return a copy pastable dialogue

---

cScripts/cScripts_postInit.sqf
cScripts/functions/init/fn_init_eventHandlers.sqf

- Added more stable eventhander for player connections and logging

Added more stable eventhander for player connections and logging

---

.github/workflows/testing.yml

Fixed check tilted not running commands after "&" symbol

---

Compositions/1.Cav_Viking_Platoon/composition.sqe

Messed up slotting order sorted out

Fixed slotting order Viking

---

cScripts/functions/gear/fn_gear_saveLoadout.sqf

- Fix a grammar issue in fn_gear_saveLoadout

Fixed grammar when loadout is saved

---

cScripts/Loadouts/CfgLoadouts_Special.hpp

- Fixed bad class colon warnings

Fixed bad class colon warnings

---

cScripts/functions/civ/fn_civ_init.sqf
cScripts/functions/gear/fn_gear_selectLoadout.sqf
cScripts/functions/gear/fn_gear_setupRadios.sqf
cScripts/functions/init/fn_init_skillAdjustment.sqf
cScripts/functions/modules/fn_zenModule_callEndex.sqf
cScripts/functions/modules/fn_zenModule_enableUnitSimulation.sqf
cScripts/functions/modules/fn_zenModule_resetPlayerRadio.sqf
cScripts/functions/players/fn_player_setOrganization.sqf
cScripts/functions/players/fn_setRadioChannel.sqf
cScripts/functions/systems/fn_addObjectToCurator.sqf
cScripts/functions/systems/fn_isValidFaction.sqf
cScripts/functions/vehicle/fn_vehicle_addCosmeticSelection.sqf
cScripts/functions/vehicle/fn_vehicle_addRegearAction.sqf
cScripts/functions/vehicle/fn_vehicle_addRepairAction.sqf
cScripts/functions/vehicle/fn_vehicle_applyLoadout.sqf
cScripts/functions/vehicle/fn_vehicle_setRadio.sqf

- A general sweep of Grammar, mainly focusing on has/have.
- A couple of spelling mistakes also fixed.

Fixed grammar and spelling in multiple files
